### ISSUE TITLE
Automatic casting of nested DTO's on multiple levels does not work

### ISSUE THREAD

**Issue by jorenvh** [spatie/data-transfer-object#108]
**ENV Info**
- php 7.3
- package version: 1.13.3

To start I would like to mention that I think that my issue is what the author of issue #102 meant.

My setup exists out 3 DTO's: Order, Buyer & Address. Where everything starts within the order DTO. Think about it like this: An order has a buyer and a buyer has an address.

**The exception:**

```
Invalid type: expected `App\Domain\Service\DataTransferObjects\BuyerData::address` to be of type `\App\Domain\Service\DataTransferObjects\AddressData`, instead got value `array`, which is array.
```

**The code:**

```php
$orderAttributes = array[....];
new OrderData($orderAttributes)
```

```php
<?php

namespace App\Domain\Service\DataTransferObjects;

use Spatie\DataTransferObject\DataTransferObject;

class OrderData extends DataTransferObject
{
   // ...

    /** @var \App\Domain\Service\DataTransferObjects\BuyerData */
    public $buyer;

   // ...
}

```

```php
<?php

namespace App\Domain\Service\DataTransferObjects;

use Spatie\DataTransferObject\DataTransferObject;

class BuyerData extends DataTransferObject
{
    // ...

    /** @var \App\Domain\Service\DataTransferObjects\AddressData */
    public $address;
}
```

```php
<?php

namespace App\Domain\Service\DataTransferObjects;

class AddressData
{
    /** @var string */
    public $address;

    /** @var string */
    public $postal;

    /** @var string */
    public $city;

    /** @var string */
    public $state;

    /** @var string */
    public $country;
}

```

**Conclusion**
Automatic casting of nested DTO's works on the first level, but throws an exception on deeper levels

**Comment by jorenvh** [comment]
Damnit, the AddressData class is not extending DataTransferObject 🤦‍♂️

Ofcourse I see this only after testing quite some scenario's and writing an issue on Github 🤦‍♂️

**Comment by oliver-la** [comment]
Thanks to you I learned that all classes have to extend the DataTransferObject, not just the "root" class. 😄
