### ISSUE TITLE
Dealing with relationships

### ISSUE THREAD

**Issue by gpassarelli** [spatie/data-transfer-object#110]
First of all, thanks for the awesome package.

Sorry to open an issue for this, but as I tried to find everywhere(your blog post, the documentation, past issues, etc) how to handle this but I couldn't find it.

On the ReadMe file, you explain we can set the DataTransferObject with the $author prod typed as an Eloquent Model

    /** @var \Author */ 
    public $author;

But later on the DataTransferObject constructor you use **author_id** and not **author**:
`'author_id' => '…',`

I understand the part when it is instantiated using`DataTransferObject::fromRequest()`, that finds the model from the input **author_id**, but when I'm creating as a `new DataTransferObject()` it won't work as I don't have a prop named **author_id** typed as int, and only **author** typed as \Author.

What would be the best way to deal with relationships and DTOs?

Should I deal only with the foreign key, as `author_id`, should I have the full class as `author`, should I have both?

Should I add on the __construct method to find this Author, like this:

    public function __construct(array $parameters = [])  
    {  
	    if ($parameters['author_id']) {  
	      $parameters['author'] = Author::find($parameters['author_id']);  
	      unset($parameters['author_id']);  
	    }
	      
        parent::__construct($parameters);  
    }

Should I have both properties on the DataTrasferObject class, like this:

    class PostData extends DataTransferObject
    {
	     /** @var string */
	     public $title;
      
	     /** @var string */
	     public $body;
      
	     /** @var \Author */
	     public $author;
     
	     /** @var int */
	     public $author_id; 
    }

What is the best approach for these scenarios?

**Comment by brendt** [comment]
I've done both in the past, depending on what context I'd use a DTO in. If it's used in actions that perform lots of business logic, chances are you'd need `Author` anyway. If it's used to store data in the database, `author_id` should suffice.
