### ISSUE TITLE
Support for self/static

### ISSUE THREAD

**Issue by jpnut** [spatie/data-transfer-object#111]
Currently any references to `self` or `static` as type hints or type declarations do not work. When normalising the type, it is converted to a string. That means when we call `assertValidType`, we check if `$value` is an instance of `'self'` or of `'static'`. (To be absolutely clear, I'm referring to `static` here not in the sense of a static property but as a reference to the called class).

I did a small investigation, the changes required to implement this would be small but they would necessitate an api change for the `FieldValidator` abstract class (and thus the implementations).

For example, one solution could be: when normalising the type, first check to see if the type is `'self'` or `'static'`. For `self`, we should return the class which declares the property. For `static` we should return the class we are validating (hence the api change).

Some thoughts: supporting `self` alone is very low priority since `self` can always be replaced by the class name. `static`, on the other hand, cannot be replaced in general. The way I see it, if you decided to support `static`, it would then make sense to support `self` too. 

As an example usage of `static`, consider the following:

```php
abstract class Foo extends DataTransferObject
{
    /**
     * @var static|null
     */
    public $child;
}

class Bar extends Foo
{
    public string $baz;
}

$bar = new Bar([
    'child' => [
        'baz' => '...'
    ],
    'baz' => '...',
]);
```

In the above, `child` is resolved to an instance of `Bar`.

If this is something the package should support, I'd be happy to submit a PR.

Thanks for your work on this package, it's a pleasure to use! 👍

**Comment by brendt** [comment]
How would you know what concrete class should be used as the `static` one though? 

Take the following example:

```php
class A extends DataTransferObject
{
    /** @var static|null */
    public $staticProp;
}

class StaticB extends A 
{
    public string $name;
}

class StaticC extends A 
{
    public string $name;
}

$a = new A([
    'staticProp' =>  [
        'name' => 'test' // Is this StaticB or StaticC?
    ],
]);
```

There's no way to know this, that's the nature of static.

**Comment by jpnut** [comment]
In your example, surely `staticProp` should be resolved to an instance of A? It would only be resolved to `StaticB` or `StaticC` if those classes were constructed explicitly.

Consider for a moment an example using the same structure as yours above, but with 

```php
class A extends DataTransferObject
{
    /** @var \A|null */
    public $a;
}
```

instead. Then the following are all valid:

```php
$a = new A([
    'a' =>  [], // This is resolved to an instance of A
]);

$b = new A([
    'a' => new StaticB([
        'name' => 'test'
    ])
]);

$c = new StaticC([
    'a' => new StaticB([
        'name' => 'test'
    ]),
    'name' => 'test'
]);
```

The point here is: we can manually set `a` to be any instance or extension of A we choose. However, if we pass through an array, this package will always resolve `a` as a new instance of `A`. Going back to `static`, the situation is exactly the same, except we only know how it will be resolved at call time. If we go back to the structure you described:

```php
$a = new A([
    'staticProp' =>  [], // This is resolved to an (empty) instance of A
]);

$b = new StaticB([
    'staticProp' => [
        'name' => 'test' // This is resolved to an instance of StaticB
    ],
    'name' => 'test'
]);

$c = new StaticC([
    'staticProp' => new StaticB([
        'staticProp' => [
            'name' => 'test' // This is resolved to an instance of StaticB
        ],
        'name' => 'test'
    ]),
    'name' => 'test'
]);
```

**Comment by brendt** [comment]
In many cases `A` would be an abstract class, which cannot be instantiated. What would happen then?

**Comment by brendt** [comment]
I gave it another read, I get your point now. You're free to submit a PR!

**Comment by brendt** [comment]
Further discussion in #112
