### ISSUE TITLE
Support extending FieldValidator?

### ISSUE THREAD

**Issue by ArondeParon** [spatie/data-transfer-object#114]
## Problem that I am trying to solve:

I want to be able to cast properties to enum instances. The [enum library](https://github.com/marc-mabe/php-enum) I am using (sorry, not Spatie this time!) does not have a public constructor, so I need to initialise these objects using a static method.

As far as I can see, I would have to create custom logic in `FieldValidator` for this so that I can detect whether a property annotation hints an `Enum` type.

If I would want to do this, I would have to:
- Extend the `DataTransferObject`
- Override `getFieldValidators`
- Extend `FieldValidator`
- Override `FieldValidator::fromReflection`.

Of course, I _could_ do this, but it feels like extending so much leaves us with a high risk of regressions if the library is updated.

The same actually applies to things like casting objects to `Carbon` instances, for example.

## Possible solutions
- Implement a `getFieldValidator` method on `DataTransferObject`, just like `getValueCaster`
- The above: override the entire chain.
- Something else; am I thinking too hard?

Would love to hear your thoughts on this.

## Ideal end-goal

Ideally, I'd be able to do stuff like this:

```php
class Person extends DataTransferObject
{
    /** @var int */
    public $id;

    /** @var \Carbon\Carbon */
    public $creationDate;

    /** @var \Enum\Gender */
    public $gender;
}
```

**Comment by mfn** [comment]
I tried to improve the situation for such cases, see https://github.com/spatie/data-transfer-object/pull/76

Since I was lucky and really only needed a specific class (CarbonImmutable) I submitted some PRs to ensure the flexibility so I can override `castValue` which in my case was enough:
```php
abstract class DTO extends FlexibleDataTransferObject
{
    /**
     * - The key is the type of the property
     * - The callable receives the value and may return the same or a different value
     * @var array<string,callable>
     */
    public static array $makers = [
    ];

    /**
     * @inheritDoc
     */
    protected function castValue(ValueCaster $valueCaster, FieldValidator $fieldValidator, $value)
    {
        if (is_array($value)) {
            return parent::castValue($valueCaster, $fieldValidator, $value);
        }

        return $this->makeValue($fieldValidator, $value);
    }

    /**
     * @param FieldValidator $fieldValidator
     * @param mixed $value
     * @return mixed
     */
    protected function makeValue(FieldValidator $fieldValidator, $value)
    {
        foreach ($fieldValidator->allowedTypes as $type) {
            $type = ltrim($type, '\\');

            if (!isset(self::$makers[$type])) {
                continue;
            }

            return self::$makers[$type]($value);
        }

        return $value;
    }
}
```
I only initialize this once during boot of the application, like this:
```php
        DTO::$makers[CarbonImmutable::class] = fn ($value): CarbonImmutable => CarbonImmutable::make($value);
```
Works surprisingly well, but it's also a _very_ simple use-case.

**Comment by brendt** [comment]
I don't think this kind of type juggling is something we want to support in the DTO package. It's true that casts work for DTO-classes, which I find an edge case, personally I'd rather not support them but people seem to like that approach.

The goal of this package is to provide type safety for your data. If you want to cast all kinds of values, I think some kind of generic DTO factory should be the way to go. 

I'm open to hear you opinion, feel free to try and change my mind, but for now I'm closing this issue.
