### ISSUE TITLE
lumen version is 5.52  could not be installed

### ISSUE THREAD

**Issue by niwsmbulai1989** [spatie/data-transfer-object#115]
`
Using version ^1.13 for spatie/data-transfer-object
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package laravel/lumen-framework (locked at v5.5.2, required as 5.6.*) is satisfiable by laravel/lumen-framework[v5.5.2] but these conflict with your requirements or minimum-stability.
  Problem 2
    - The requested package tymon/jwt-auth (locked at 1.0.0-rc.1, required as 1.0.0-rc.5) is satisfiable by tymon/jwt-auth[1.0.0-rc.1] but these conflict with your requirements or minimum-stability.
  Problem 3
    - Conclusion: don't install laravel/lumen-framework v5.6.4
    - Conclusion: don't install laravel/lumen-framework v5.6.3
    - Conclusion: don't install laravel/lumen-framework v5.6.2
    - Conclusion: don't install laravel/lumen-framework v5.6.1
    - Conclusion: don't install laravel/lumen-framework v5.6.0
    - Conclusion: remove illuminate/auth v5.5.44
    - Installation request for laravel/lumen-framework 5.6.* -> satisfiable by laravel/lumen-framework[5.6.x-dev, v5.6.0, v5.6.1, v5.6.2, v5.6.3, v5.6.4].
    - Conclusion: don't install illuminate/auth v5.5.44
    - laravel/lumen-framework 5.6.x-dev requires illuminate/auth 5.6.* -> satisfiable by illuminate/auth[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - Can only install one of: illuminate/auth[5.6.x-dev, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.0, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.1, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.10, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.11, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.12, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.13, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.14, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.15, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.16, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.17, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.19, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.2, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.20, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.21, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.22, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.23, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.24, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.25, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.26, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.27, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.28, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.29, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.3, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.30, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.31, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.32, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.33, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.34, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.35, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.36, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.37, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.38, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.39, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.4, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.5, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.6, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.7, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.8, v5.5.44].
    - Can only install one of: illuminate/auth[v5.6.9, v5.5.44].
    - Installation request for illuminate/auth (locked at v5.5.44) -> satisfiable by illuminate/auth[v5.5.44].
Installation failed, reverting ./composer.json to its original content.
`

**Comment by brendt** [comment]
This has nothing to do with this package, but a version conflict between `tymon/jwt-auth` and `laravel/lumen-framework`. 

You can use `composer why`  and `composer why-not` to debug such problems.

**Comment by niwsmbulai1989** [comment]
How to solve this problem? Is the lumen version too low?

**Comment by brendt** [comment]
I'm sorry but I'm not here as a supportline for all PHP related problems :) My suggestion would be to read up on how to debug composer version conflicts, I'm sure google will be able to help.
