### ISSUE TITLE
Automatic casting of nested array DTOs doesn't work with DataTransferObjectCollection

### ISSUE THREAD

**Issue by morrislaptop** [spatie/data-transfer-object#116]
```php
class TagData extends DataTransferObject
{
   public string $name;
}

class TagDataCollection extends DataTransferObjectCollection
{
    public function current(): TagData
    {
        return parent::current();
    }
}

class PostData extends DataTransferObject
{
   public TagDataCollection $tags;
}

$postData = new PostData([
    'tags' => [
        ['name' => 'foo'],
        ['name' => 'bar']
    ]
]);
```

Would you be open for a PR?

**Comment by mfn** [comment]
Would the idea to introduce special checks for `DataTransferObjectCollection` to handle this?

**Comment by morrislaptop** [comment]
Yep - see if the type extends `DataTransferObjectCollection` then get the type from the `current` method and try to cast to that...

**Comment by mfn** [comment]
Aha, that's the catch! From the readme at https://github.com/spatie/data-transfer-object/#working-with-collections
> By overriding the current method, you'll get auto completion in your IDE. Alternatively you can also use a phpdoc for this:
> ```php
> /**
>  * @method PostData current
>  */
> class PostCollection extends DataTransferObjectCollection
> {
> }
```
So just checking the method may not be enough to legitimately derive the type.

Btw what's the plan if no type can be derived, from neither the `current`-method (e.g. not implemented) nor a phpdoc (e.g. missing)?

(PS: looking forward to have this included btw 😄 )

**Comment by brendt** [comment]
It's an interesting feature, but we'd need a good way to handle edge cases when no DTO can be inferred. In fact, I needed this feature in `laravel-data-transfer-object`, to be able to support custom Eloquent casts. I added `collectionFor` method, which basically tells you which DTO it's a collection for.

We could add it as a requirement in the DTO package, but it would be a breaking change, and it would add more boilerplate code. Not sure that's something we want.

**Comment by aidan-casey** [comment]
@brendt - Would there really be anything inherently wrong with simply stating in the docs that the feature is only supported by typing the collection class and checking the return type of `current()` and `offsetGet()`? If a type cannot be found and the value passed doesn't match it, an exception could be thrown accordingly..

**Comment by brendt** [comment]
@aidan-casey I agree, if we can't infer the type by looking at `current()` or `offsetGet`, let's just throw an exception. 

@morrislaptop are you up for changing the PR?

**Comment by morrislaptop** [comment]
Sure, one mo!

**Comment by morrislaptop** [comment]
Just to confirm, the PR already throws an exception if it can't infer a type from `current`, so the changes are:

* Update from master
* Try to infer a type from offsetSet() as well

**Comment by brendt** [comment]
Awesome, let's continue this converstation in the PR!
