### ISSUE TITLE
Providing more than one type option

### ISSUE THREAD

**Issue by morrislaptop** [spatie/data-transfer-object#118]
Is there the ability to do anything like https://github.com/typestack/class-transformer#providing-more-than-one-type-option?

```php
<?php

class Photo {
    public int $id;
    public string $filename;
}

class Landscape extends Photo {
    public bool $panorama;
}

class Portrait extends Photo {
    public Person $person;
}

class UnderWater extends Photo {
    public int $depth;
}

class Album
{
     public int $id;
     public string $name;
     public Photo $photo;
}

$arr = [
  "id" => 1,
  "name" => "foo",
  "topPhoto" => [
      "id" => 9,
      "filename" => "cool_wale.jpg",
      "depth" => 1245,
      "__type" => "Underwater"
  ]
];

**Comment by mfn** [comment]
Nothing like this is currently built-in.

The "suggested way" would be to catch this in the DTOs constructor by inspecting the payload and massage/cast the incoming data as necessary.

**Comment by brendt** [comment]
I don't think this is something the package should support. If you want to automate it, I'd suggest to build custom DTO factories.
