### ISSUE TITLE
Working with collections

### ISSUE THREAD

**Issue by chrisrhymes** [spatie/data-transfer-object#119]
I have found this package very useful, thank you. I just have a question about working with collections. If I use the example in the docs of the post data then should I be able to pass in the json, such as an array of post data objects, and get a collection returned? 

```php
$postCollection = new PostCollection($json);
```

I do get a collection returned, but instead of being a collection of objects it returns a collection of arrays. This means I cannot do `$postCollection[0]->title` as it says cannot get property of non object. 

Also, I'm using PHPStorm and it doesn't provide any autocompletion, either with a collection or a single object? 

I am using PHP 7.4 and version 2.2.1 of the package. Thanks.

**Comment by mfn** [comment]
The constructor already needs to receive the collection as the correct type, [please refer to this part in the readme](https://github.com/spatie/data-transfer-object#working-with-collections):

> Of course you're free to implement your own static constructors:
> ```php
> class PostCollection extends DataTransferObjectCollection
> {
>     public static function create(array $data): PostCollection
>     {
>         return new static(PostData::arrayOf($data));
>     }
> }
> ```

**Comment by chrisrhymes** [comment]
Thank you for your help!

**Comment by mfn** [comment]
You're welcome!

I think in hindsight the most important piece next to the custom constructor is in fact the `arrayOf` helper method; maybe it should be more emphasized in the docs.

**Comment by naneri** [comment]
@mfn I don't get, if I have an array with few entity data, where do I pass it? 
Does not work when I am passing it to the create() method.
