### ISSUE TITLE
How to retrieve a value in a nested array?

### ISSUE THREAD

**Issue by mvdhoek1** [spatie/data-transfer-object#120]
Given this code snippet: 

```
class PostData extends DataTransferObject
{
    /** @var array */
    public $title;
}

$array = [
        'type' => 'type',
        'title' => 
           [ 'rendered' => 'Update: coronavirus in MO, VO en BW']
];

$postData = new PostData($array);
```

Now when I dump `$postData->title` it will return an array:

```
array (size=1)
  'rendered' => string 'Update: coronavirus in MO, VO en BW' (length=35)
```

Is it possible to retrieve the value of 'rendered' directly?

Any help would be appreciated :)

**Comment by mfn** [comment]
- create another DTO, e.g. `PostDataTitle extends DataTransferObject`
- use FQCN to refer to it in `@var \App\…\PostDataTitle`

that should do it, unless I made a mistake.

Basically it's this part of the readme => https://github.com/spatie/data-transfer-object#automatic-casting-of-nested-dtos
