### ISSUE TITLE
Allow integers in float fields

### ISSUE THREAD

**Issue by bastien-phi** [spatie/data-transfer-object#122]
I don't know if this is a legitimate issue but using version 2.2.1, I can't pass an integer to a float field.
```
class MyDTO extends DataTransferObject {
    public float $foo;
}

new MyDTO(['foo' => 42]);
```
doesn't work. 
```
Spatie\DataTransferObject\DataTransferObjectError : Invalid type: expected `App\MyDTO::foo` to be of type `double`, instead got value `42`, which is integer.
```
Of course, I could just do `new MyDTO(['foo' => 42.0]);` or `new MyDTO(['foo' => (float) 42]);` but I wondered if this behavior was the one wanted as php allows to 
```
class Bar {
    private float $baz;

    public function __construct(float $baz)
    {
        $this->baz = $baz;
    }
}

new Bar(12);
```
Would you be open to allow such things in this package ?

**Comment by mfn** [comment]
Isn't the problem the loss of information? See https://3v4l.org/kOVYA

It the package would do that, it "could" loose information.

Unless I'm missing something, IMHO this has to be done explicitly.

**Comment by bastien-phi** [comment]
Transforming a float to an integer can loose information indeed.

My point here is not about accepting float for an integer attribute but accepting an integer for a float attribute. I can't see how you can loose information here.

My problem comes from serialization/de-serialization where `.0` is not always kept in jsons (for example https://3v4l.org/WLVKK) and I cannot always control or manually convert ints to floats.

**Comment by mfn** [comment]
> but accepting an integer for a float attribute. I can't see how you can loose information here.

Please look at https://3v4l.org/kOVYA again, it shows you that the conversion from integer to float also looses information:

- value is PHP_INT_MAX, i.e. depending on your arch it can be `9223372036854775807`
- you convert it to float => `9.2233720368548E+18`
- you cannot get back the original int value, you lost information because it became `-9223372036854775808` :boom:

**Comment by bastien-phi** [comment]
Ok. So you think that the package should be stricter than php ?

**Comment by brendt** [comment]
> So you think that the package should be stricter than php ?

Yes, that's the goal of the package: provide stricter type checks than PHP :) It's true that PHP allows to mix integers and floats, but this package doesn't. 

You should indeed explicitly cast the value if you want to mix them.

**Comment by bastien-phi** [comment]
I will stick with 
```
class MyDTO extends DataTransferObject {
    /** @var float|int */
    public float $foo;
}
```
event if it does not make sense.

I don't always control how serialization is done and the fact that `json_encode(['foo' => 42.0])` gives `{"foo": 42}` bugs me. I know it is possible to use `JSON_PRESERVE_ZERO_FRACTION` but working with a public API does not ensure that it will be the case.

In fact, even working with my own data can be problematic as requests from  javascript client are not serialized with the decimal part when it's 0 : `JSON.stringify({"foo": 42.0})` gives `{"foo":42}`.
