### ISSUE TITLE
README.md update to match PHP 7.4

### ISSUE THREAD

**Issue by rihardssceredins** [spatie/data-transfer-object#124]
Hey!

First off - lovely package (as always)! 💯

Would be really nice if README.md could be updated with the current preferred standart on how to use DTOs after 7.4 was released and the package's minimum required PHP version was bumped to 7.4. Currently on the README.md it still says: 

> When PHP 7.4 introduces typed properties, you'll be able to simply remove the doc blocks and type the properties with the new, built-in syntax.

**Comment by brendt** [comment]
Feel free to submit a PR! Otherwise I'll look at it later this week

**Comment by rihardssceredins** [comment]
@brendt I'd love to but I would be guessing about the implementation/way you imagined it for PHP 7.4. For example, do you still support doc blocks (i could look it up, i know) or since requiring PHP 7.4 you only support typed properties/recommend going with typed properties where possible? Lets say in this case:

```
/**
     * Lists of types: 
     *
     * @var \App\Models\Author[]
     */
    public $property;
```

**Comment by mfn** [comment]
@rihardssceredins yes, they're still supported. This is due to the fact that PHP property types are more limited so phpdoc has even precedence to provide more specific/strict type information.
