### ISSUE TITLE
[Question] What's the recommended way to upload files?

### ISSUE THREAD

**Issue by JunaidQadirB** [spatie/data-transfer-object#125]
I've just started using the package. so I have an existing form to create/update posts with a `featured_image`  field along with, `title`, 'slug', and `body`. 

With form requests, I have the option to pass the request to my action and check the existence of a file via `hasFile` method. 

What is the recommended way to upload files using DTOs and actions?

**Comment by brendt** [comment]
I'd store the file first, and pass the path to the DTO
