### ISSUE TITLE
Watch changed properties

### ISSUE THREAD

**Issue by aidan-casey** [spatie/data-transfer-object#127]
@brendt, my gut tells me you are going to hate this idea, but it was fresh on my mind and I figure worse case I will just be set straight on how we should accomplish this functionality. 😀

Currently there are several useful methods that exist on the `DataTransferObject` class. For example, we have `all()`, `only()`, and `except()` which help us retrieve _only_ the data we need to. There is not a way to retrieve changed properties though, and I think this could be useful functionality.

The best way I can see to achieving this would be through an observer class. This could be called either through a `watch()` method on the DTO class or static method on the observer. I have placed a simple and untested example below.

```php
class DataTransferObjectObserver
{
    protected DataTransferObject $dto;
    protected array $changed = [];

    public function __construct(DataTransferObject $dto)
    {
        $this->dto = $dto;
    }

    public function __call($method, $arguments)
    {
        return call_user_func_array([$this->dto, $method], $arguments);
    }

    public function __get($property)
    {
        return $this->dto->{$property};
    }

    public function __set($property, $value)
    {
        if (! in_array($property, $this->changed)) {
            $this->changed[] = $property;
        }

        $this->dto->{$property} = $value;
    }

    public function changed()
    {
        return call_user_func_array([$this->dto, 'only'], $this->changed);
    }
}
```

As you can see, the observer simply acts as a wrapper class for the main DTO and gives us an extra `changed()` method so we can see what properties have been messed with.

Thoughts?

**Comment by mfn** [comment]
Personally I would rather not even have this helper methods there and keep the lib as slim as possible no-features-attached. My 2c 😏

**Comment by aidan-casey** [comment]
That is fair and I get the sentiment, but this package did kinda go down that road when the existing ones were implemented.

**Comment by brendt** [comment]
> did kinda go down that road when the existing ones were implemented

I know and I regret that, but in some cases people just kept asking for specific features.

Anyways, you're right, I hate it — just kidding. 

To be fair I really appreciate you putting time and effort thinking about this idea. I realise there might be cases where this functionality is useful. But, as I'm afraid it'll be the same answer as for many others: this functionality is out of scope for this package.

What I would do, if I were you, is to make an abstract class, extending from the base DTO class, and do whatever you like in it. You could do this in your project, or make a package for it yourself. We actually add functionality to our DTOs in our projects this way, and it works fine! Hope that helps.

**Comment by aidan-casey** [comment]
Totally get it and I think that’s reasonable. I appreciate you taking the time to review!
