### ISSUE TITLE
phpstan and checkUninitializedProperties

### ISSUE THREAD

**Issue by mfn** [spatie/data-transfer-object#129]
Today phpstan https://github.com/phpstan/phpstan/releases/tag/0.12.33 was released, bringing us:
> Check uninitialized typed properties that aren't set in the constructor (https://github.com/phpstan/phpstan-src/commit/a1eb1f5b65b62019b1d4653f9438c7591c3379a3), https://github.com/phpstan/phpstan/issues/2984
> -   Off by default, needs checkUninitializedProperties: true.

This bombs on any DTO with require fields as they're detected as being un-initialized 😅

> Class App\DTO\SomeDTO has an uninitialized property $id. Give it default value or assign it in the constructor.

For this library this static analysis doesn't matter as a DTO with required fields will never incorrectly created.

I'm creating this issue to discuss what best practices we can provide here:
- tell people to just ignore it (e.g. baseline)
  Could be annoying when DTO changes
- come up with a configuration to ignore this particular rule for anything extending from `\Spatie\DataTransferObject\DataTransferObject`
- custom phpstan rule to deal with this 🤔

**Comment by mfn** [comment]
@ondrejmirtes may you can provide a recommendation? This is thanks to your latest https://github.com/phpstan/phpstan/releases/tag/0.12.33 release bringing us checkUninitializedProperties 🎉

This library here works like this, you provide:
```php
class FancyDTO extends \Spatie\DataTransferObject\DataTransferObject
{
  public int $id;
}
```
and use it like this:
```php
$dto = new FancyDTO(['id' => 123']);
```

`DataTransferObject` itself will not construct the object if such properties ("required attributes") are not provided in the payload to the constructor, e.g.
```php
$dto = new FancyDTO([]);
```
will throw an exception.

As in: this library will never create objects where public uninitialized properties can be present.

I'm using this in a  (Laravel) project where I could already fix some real bugs (thank you 🙏 ) because I enabled the rule but I use a lot of such DTOs and thus get a LOT of errors.

I can add them to the baseline, but DTOs get changed/added and this creates lots of noise.

Is it possible to ignore a rule for a certain "pattern" of file? 🤔

Or is it possible to write a rule to ignore other rules 😅

Or is it possible to mark descendants of `DataTransferObject` save for this, similarly as you marked phpunits `setUp` as constructor?

Thanks for any pointers 😄

**Comment by mfn** [comment]
I just realized https://phpstan.org/blog/detecting-unused-private-properties-methods-constants mentions how to customize this (I skipped this initially because I was only interested in the next chapter "One more thing").

Seems there's an interface which can be implemented https://github.com/phpstan/phpstan-src/blob/587943766fbcfda7651d6728b544011dcb5063f2/src/Rules/Properties/ReadWritePropertiesExtension.php

Though not sure, I wouldn't be interested in `isAlwaysRead` and `isAlwaysWritten` as this should still be resolved by phpstan, only `isInitialized`.

I tried this naive approach:
```php
class DataTransferObjectPopertiesAreAlwaysInitializedExtension implements ReadWritePropertiesExtension
{
    public function isAlwaysRead(PropertyReflection $property, string $propertyName): bool
    {
        return false;
    }


    public function isAlwaysWritten(PropertyReflection $property, string $propertyName): bool
    {
        return false;
    }

    public function isInitialized(PropertyReflection $property, string $propertyName): bool
    {
        return $this->extendsOurDTO($property->getDeclaringClass());
    }

    private function extendsOurDTO(ClassReflection $class): bool
    {
        while ($parentClass = $class->getParentClass()) {
            if ($parentClass->getName() === DataTransferObject::class) {
                return true;
            }
        }

        return false;
    }
}
```
but then phpstan didn't finish 😅
```
> phpstan analyse --configuration=phpstan.neon app
  500/1073 [▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░]  46%

  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "phpstan analyse --configuration=phpstan.neon app" exceeded the timeout of 300 seconds.
```

**Comment by ondrejmirtes** [comment]
@mfn You're on the right track! 👍 

I don't see it on the first look either, but it looks like your code contains an infinite loop or something. You can simply write this instead:

```php
    public function isInitialized(PropertyReflection $property, string $propertyName): bool
    {
        return $property->getDeclaringClass()->isSubclassOf(DataTransferObject::class);
    }
```

And it should do what you want.

**Comment by mfn** [comment]
@ondrejmirtes it works 😅

I thought so too about the infinite loop but you beat me in time here, thank you 🙏 

One more question though, as it's not clear to me:
- for `isAlwaysRead` and `isAlwaysWritten` means simply => defer the evaluation to phpstan?
- for `isInitialized` returning false… what does it mean?

My concern is that, whilst I use the above extension to tell phpstan for certain classes that "yes, those properties are initialzied", how is the `false` signaling phpstan that "wait, the answer isn't 'no' but rather 'evaluate yourself'' 🤔

thanks

**Comment by mfn** [comment]
Or to reprehase it: how does such an extension only wanting to deal with a certain of classes in the hierarchy can signal phpstan that "take care of all the others the way you usually do"?

**Comment by ondrejmirtes** [comment]
Returning `false` from the extension does the same thing as if there wasn't any extension at all :)

**Comment by mfn** [comment]
@brendt would you consider adding a phpstan rule with explicit support for this to the package, so projects using phpstan can directly take advantage of this? would be a "suggests" feature though, I wouldn't add a real phpstan dependency.

**Comment by brendt** [comment]
Ah yes, looks like a good idea, thanks @mfn and @ondrejmirtes for looking into this!

@mfn I'm not sure what the best approach is here, should we add the rule in this package, or should we make another package and add it as a composer suggest? I'm fine with both, would love to hear your feedback!

**Comment by mfn** [comment]
I did briefly think about a standalone package but … ok I'm all for "modularity" but that adds an immense amount of overhead for just a few lines of code as it is right now :)

Maybe if "more" is needed we could expand, otherwise I would first see if integration in this package can be done meaningful?

That important bit would still be that we add at least CI tests for this but we wouldn't add phpstan as dependency by default (well, unless this package wants to endorse it, not sure what @brendt plans are regarding static analysis).

**Comment by ondrejmirtes** [comment]
You could add the extension code to this repo and add `extension.neon` that enables it + add the entry to composer.json that allows it to be installed with https://github.com/phpstan/extension-installer without having to declare dependency on phpstan/phpstan in `require`, however:

1) You'd have to have `phpstan/phpstan` in `require-dev` to both being able to develop the extension + being able to analyse the whole codebase with PHPStan :)
2) There's still a problem as the user might install it alongside incompatible version of PHPStan and the extension wouldn't work. Even worse, it'd break the execution of PHPStan because the `ReadWritePropertiesExtension` interface wouldn't exist.

So the extra package just with the extension might be a good idea anyway...

**Comment by mfn** [comment]
I created PR https://github.com/spatie/data-transfer-object/pull/135 based on https://github.com/spatie/data-transfer-object/issues/129#issuecomment-66235797 I decide to go for inclusion in this repo for now, as I'm not keen managing a dedicated package for this small amount of code.

**Comment by brendt** [comment]
Released as 2.3.0: https://github.com/spatie/data-transfer-object/releases/tag/2.3.0

**Comment by mfn** [comment]
Awesome!

Before, I had
```
 [ERROR] Found 152 errors
```
Now => none :)

Thanks for cutting a release so quickly!

**Comment by brendt** [comment]
Great!
