### ISSUE TITLE
Questions on correct usage

### ISSUE THREAD

**Issue by hosmelq** [spatie/data-transfer-object#134]
Hello

This is a question on the correct usage of this package for updating data.

I have some nullable fields in my DB and I would like to know what is the best way to pass data with a DTO without losing existing data.

In the following example, the client can send partial data, for example, if the client only sends the `name` field the `birthday` will be null and the record in the DB will be updated with null.

**StudentData**

```php
class StudentData extends DataTransferObject
{
	/** \Carbon\Carbon|null */
    public $birthday;

	/** string */
    public $name;    
    
	...

	public static function fromRequest(StudentRequest $request) {
		return new self(
			[
				'name' => $request->input('name'),
				'birthday' => $request->input('birthday'),
				...
			]
		);
	}
}
```

**UpdateStudentAction**

```php
class UpdateStudentAction {
	public function execute(Student $student, StudentData $data) {
		$student->update(
			$data->toArray()
		);

		...
	}
}
```

**Comment by mfn** [comment]
Looks good to me, that's the way I use it too.

**Comment by hosmelq** [comment]
Yes @mfn, but I lose some database data as the example i mentioned.

**Comment by mfn** [comment]
Sorry I don't follow.

This library is rather simple and allows to pass grouped data around and has some niceties regarding instantiating them based nested array payload structures with basic auto-type checking.

Everything else is up to the developer, how to deal with partial data, etc.

**Comment by hosmelq** [comment]
> Everything else is up to the developer, how to deal with partial data, etc.

Yes, I know, so this is a question, not an issue.

**Comment by brendt** [comment]
If the client sends partial data, you'll have to either

- Make separate DTOs to handle those cases separately
- Manually check which fields to save, depending on whether they are nullable or not. 

We've used option one, but we only have a limited set of partial DTOs, so it's manageable. If we're talking tens of fields, and every one of them could be sent or not, I don't think this package will be able to solve that, unless you provide an explicit `Omitted` value. Hope that helps!

**Comment by Rezrazi** [comment]
Sorry for bumping this issue, I was just looking to share a way I found to update a model taking into account omitted or unchanged attributes.

This can be done by creating an array of omitted attributes, right before triggering the `$model->update()` method.

_Note_ that I wrote this as an `Action` which are callable classes with a single static function that our codebase uses, however you can go about this in any way you want.

```php
class CollectNullValuesAction
{
    public static function handle(ModelDTO $data): array
    {
        $output = [];
        foreach (get_object_vars($data) as $name => $value) {
            if ($value == null)
                array_push($output, $name);
        }

        return $output;
    }
}
```

and then using this array when updating like this

```php
$data = ModelDTO::fromRequest($request);
$omit = CollectNullValuesAction::handle($data);

$model->update($data->except(...$omit)->toArray());
```

This requires spread operators, so any version of `php^7.4` should work. And you need to mark your members as nullable in your DTO, ie. `public ?string $name`

I hope this helps.

**Comment by cdomigan** [comment]
@Rezrazi thanks for sharing that approach. It looks like that wouldn't let you then support null values? It would interpret them all as omitted?

Ideally I would love a way to support both null and omitted values.
