### ISSUE TITLE
[Proposal] Add class-based factories for DTO

### ISSUE THREAD

**Issue by bastien-phi** [spatie/data-transfer-object#144]
I often use fake dto in my tests and love Laravel 8 model factories.

I finally came up with writing a base factory for data transfer objects (based on Laravel 8 factories).

I wonder if this could be added to this package. My main concern is the fact that the package does not have any dependency but adding the factory feature would imply adding `fzaninotto/faker` as a dependency.

Let me know what you think about that, I can send a PR for that.

**Comment by brendt** [comment]
I'm actually working on a separate laravel-specific DTO pacakge; there's no ETA but I'll make sure to look into supporting it. 

From what I gathered, L8's class based factories only work with models, isn't that the case?

**Comment by bastien-phi** [comment]
Actually yes, L8's factories only work with models. But with litle tweaks, we can keep a very similar api and provide class based DTO factories. 

The only problem is we have to copy-paste L8's factories and edit it to have a nice DTOFactory. If any new feature comes in Laravel, the DTOFactory won't have it automatically. Let me know if you want to see what changes need to be made.

It's nice to know you are working on a laravel-specific DTO package. Looking forward to see it !

Again, thanks for everything you do for the community ! :heart:

**Comment by bastien-phi** [comment]
Hi @brendt !

I just saw the 3.0 release. Congrats ! Really looking forward to use it !

It remembered me that DTO factory stuff. Is there still a plan for a laravel specific package or could I propose a PR for adding this in this package ?

**Comment by mfn** [comment]
This package has nothing to do with Laravel and thus, forgive me answering instead of Brendt, never will have Laravel specific parts.

There's an external tools section: https://github.com/spatie/data-transfer-object#external-tools

And in general the library is open to changes to support integration etc.

**Comment by bastien-phi** [comment]
I totally understand.

My point here is not to bring some Laravel specific parts but to implement a DTO Factory *inspired* by the Laravel model factories.

**Comment by brendt** [comment]
I'm still a little on the fence about this one… That's because I find very little value in Laravel factories compared to building your own (without any abstractions). In fact, I think using simple classes as factories are better since you don't have to worry about the magic happening behind the scenes, and thus not running into issues with static analysis. 

Nevertheless, I'm curious what kind of functionality you had in mind that you think would add a significant amount of value to warrant a factory abstraction?

**Comment by bastien-phi** [comment]
Basically, I would use DTO factories to unit test my actions for example.

From real project : 
```php
class EmployeeDTOFactory extends DtoFactory
{
    /** @var string */
    protected $dto = EmployeeDTO::class;

    /**
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'id' => $this->faker->unique()->uuid,
            'gender' => $this->faker->randomElement([Gender::man(), Gender::woman()]),
            'ageRange' => $this->faker->randomElement([
                AgeRange::lessThirty(),
                AgeRange::thirties(),
                AgeRange::forties(),
                AgeRange::moreFifty(),
            ]),
            'grossTotalFullTime' => $this->faker->randomFloat(2, 1_000, 1_000_000),
            'dailyIndemnity' => $this->faker->randomFloat(2, 0, 1_000),
            'seniorityBonus' => $this->faker->randomFloat(2, 0, 1_000),
            'exclusions' => $this->faker->randomFloat(2, 0, 1_000),
            'contractPresence' => $this->faker->numberBetween(150, 365),
            'genuineContract' => $this->faker->boolean(90),
            'socioProfessionalCategory' => $this->faker->randomElement([
                'Ouvriers',
                'Employés',
                'Techniciens et agents de maîtrise',
                'Ingénieurs et cadres',
            ]),
            'classification' => 'Groupe ' . $this->faker->numberBetween(1, 6),
            'absences' => $this->faker->numberBetween(0, 200),
            'pregnancy' => fn (array $attributes) => Gender::woman()->isEqual($attributes['gender'])
                ? $this->faker->boolean
                : false,
            'raiseDuringPregnancy' => fn (array $attributes) => $attributes['pregnancy'] ? $this->faker->boolean : false,
            'individualRaise' => $this->faker->boolean,
            'promotion' => $this->faker->boolean,
        ];
    }

    public function genuineContract(bool $genuine = true): self
    {
        return $this->state(['genuineContract' => $genuine]);
    }

    public function present(bool $present = true): self
    {
        return $this->state(['contractPresence' => $present ? 200 : 100]);
    }

    public function woman(): self
    {
        return $this->state(['gender' => Gender::woman()]);
    }
    
    // lot of more methods to define the attributes, you get the point
}
```
and in the test 
```php
/**
 * @test
 * @covers ::execute
 */
public function raiseAfterPregnancyAreCorrectlySet()
{
    $employees = Collection::make(
        EmployeeDTOFactory::times(5)->present()->genuineContract()->woman()->pregnancy()->raisedDuringPregnancy()->make()
        )
        ->add(EmployeeDTOFactory::new()->woman()->present(false)->genuineContract(false)->makeOne())
        ->add(EmployeeDTOFactory::new()->woman()->present()->genuineContract()->pregnancy(false)->raisedDuringPregnancy()->makeOne());
    
    app(CreateOrUpdateRaiseAfterPregnancyAction::class)->execute($this->index, $employees);

    $this->assertDatabaseHas('raise_after_pregnancies', [
        'gender_equality_index_id' => $this->index->id,
        'total' => 5,
        'raised' => 5,
        'score' => 15,
        'computable' => true,
    ]);
}
```

This case is maybe a little bit extreme but I think here the factory has some value.

**Comment by brendt** [comment]
Does your IDE or static analyser knows the exact type of the result from `EmployeeDTOFactory::times(5)->present()->genuineContract()->woman()->pregnancy()->raisedDuringPregnancy()->make()` ? Does it know it's an EmployeeDTO object?

**Comment by bastien-phi** [comment]
Well, it knows thanks to a docblock

```php
/**
 * @method \Domain\Society\DTO\EmployeeDTO makeOne($attributes = [])
 * @method array<\Domain\Society\DTO\EmployeeDTO>|\Domain\Society\DTO\EmployeeDTO make($attributes = [])
 */
class EmployeeDTOFactory extends DtoFactory
```
We can imagine any api here : 
- `makeOne` to make single DTO, and `make` to make one or many
- `makeOne` and `make` enforcing make returning an array of DTO
- `make` (single instance) and `makeMany` (multiple instances)
- ...

Creating multiple instance could return an array or something else but I'm not sure adding a dependency for that would be great
