### ISSUE TITLE
Encapsulate API response when there is a hyphen

### ISSUE THREAD

**Issue by talovicnedim** [spatie/data-transfer-object#145]
Hi @brendt,

First of all, I want to say thanks for creating such a great package. Extremely helpful in our app.

I have a question regarding encapsulating response from REST API. For example, we use Mailgun and we would like to fetch a message ID.

If you take a look at the response structure (https://documentation.mailgun.com/en/latest/api-events.html#event-structure), you will see that they have keys such as:

- log-level
- message-id
- recipient-domain

etc.

As you know, PHP doesn't support using hyphen (-) in variable names so I just wonder how to support these response keys when we cannot add these class properties.

Many thanks.

p.s. what comes to my mind is to create a method `getMessageId` and fetch it from array, but wonder if there is some other/better way?

**Comment by mfn** [comment]
You have to do this on your own: either before you pass it to the DTO or you can do it in the constructor.

I faced similar things with e.g. the Linkedin API which uses `:` in their keys 🤷‍♀️

**Comment by talovicnedim** [comment]
@mfn thanks for the suggestion! I added it the constructor of item and works great.

Here's a short example if someone needs it:

```
class MailgunItem extends FlexibleDataTransferObject
{
    public string $event;

    public ?array $delivery_status;

    public function __construct(array $item)
    {
        $this->event = $item['event'];
        $this->delivery_status = $item['delivery-status'] ?? null;
    }
}
```

**Comment by mfn** [comment]
I would suggest to only transform the incompatible keys and let the rest by done by the DTO: this makes it easier in the future to expand properties which don't have problem:
```php
    public function __construct(array $item)
    {
        $item['delivery_status'] = $item['delivery-status'];
        // Optionally unset delivery-status if it still causes issues

        parent::__construct($item);
    }
```
This can be pretty terse because you're using the `Flexible*` one which ignores untyped props. I love that one, btw 😄 

If you've many DTOs and this is a often re-curring pattern, you could also call some utility function mangling all keys automatically from `-` to `_` and pass it on to the constructor.

**Comment by talovicnedim** [comment]
Many thanks, this is even better! 😄
