### ISSUE TITLE
Cast to class when constructor is private?

### ISSUE THREAD

**Issue by ragulka** [spatie/data-transfer-object#146]
I stumbled upon an issue when trying to use `BigDecimal` from https://github.com/brick/math:

```php

use Spatie\DataTransferObject\DataTransferObject;

class MyData extends DataTransferObject {

    /** @var Brick\Math\BigDecimal|null */
    public $net_price = null;

}

new MyData(['net_price' => '10.25']);

// Invalid type: expected `MyData::quantity` to be of type `Brick\Math\BigDecimal, null`, instead got value `10.25`, which is string..

```

The issue seems to be that [BigDecimal constructor is private](https://github.com/brick/math#instantiation), which is what `ValueCaster` is [trying to use](https://github.com/spatie/data-transfer-object/blob/master/src/ValueCaster.php#L32).

I'd have to cast to `BigDecimal` using a factory: `BigDecimal::of('10.25')`. I'd like to avoid having to cast each `BigDecimal` manually before creating the DTO.

Is there any way to provide a custom caster, perhaps?

**Comment by ragulka** [comment]
Hmm, perhaps I have misunderstood what this library offers... my initial understanding was that when given an array of values, the DTO would try to cast the given values to types declared on the object. However, going through the code it seems that it will only try to cast array values, which only seems to be intended for casting nested DTOs.

I was hoping I could just throw my input to the DTO, without having to cast the values myself...

**Comment by mfn** [comment]
Hmm, no it expects the type to be matches. Aka string. That's the point of the library, no casting.

However

I had the same beef with e.g. Carbon: I know a certain field, when it's a string, I want it to be represented via https://github.com/briannesbitt/Carbon/

I still use the approach outlined in https://github.com/spatie/data-transfer-object/issues/121#issuecomment-642863130 as https://github.com/spatie/data-transfer-object/pull/76 wasn't accepted 😢

**Comment by brendt** [comment]
I'll revisit custom casts when we add support for PHP 8 :)
