### ISSUE TITLE
Data Transfer Object Factory - external tool?

### ISSUE THREAD

**Issue by aidan-casey** [spatie/data-transfer-object#148]
Hey there! We built [this](https://github.com/Anteris-Dev/data-transfer-object-factory) package that generates DTOs based on their definition. It utilizes ReflectionClass and and phpDocumentor's doc block parser to determine a property's type and faker to generate a value for that property. If a property does not have a type assigned, it will have a random type generated.

Wondering if this might be a candidate for the external tools section. If so, I am happy to PR, but otherwise that's okay too!

**Comment by mfn** [comment]
(disclaimer: Not the maintainer) but I think absolutely yes, sounds very cool. I would just make a PR to accelerate the process ;-)

**Comment by aidan-casey** [comment]
Probably not a bad suggestion. I'll get on that.
