### ISSUE TITLE
static analysis does not seems to catch mistypings on collection

### ISSUE THREAD

**Issue by crissi** [spatie/data-transfer-object#155]
`<?php
    namespace App\Services\Service;
    
    use Spatie\DataTransferObject\DataTransferObjectCollection;
    
    class ParticipantCollection extends DataTransferObjectCollection
    {
        public function current(): ParticipantObject
        {
            return parent::current();
        }
    
        public static function create(array $data): ParticipantCollection
        {
            return new static(ParticipantObject::arrayOf($data));
        }
    }`

I am running static analysis with phpstan and was expecting an error here, when accessing the unknown_value. Am I doing something wrong?

```
$participants = ParticipantCollection::create($correctData)

$participants[0]->unknown_value

**Comment by brendt** [comment]
That sounds more like a question for phpstan than for us, as far as I know it should be able to catch it by correctly implementing the return type of `current`, which you did.
