### ISSUE TITLE
Autocompletion with Laravel Collections

### ISSUE THREAD

**Issue by Albvadi** [spatie/data-transfer-object#157]
Hi,
I know this is not the right place for this question, but maybe you as expert developers who are used to working with this package together with Laravel Collections, know some way to solve it ...

Your `DataTransferObjectCollection` is fine for something simple like iterations and the IDE recognizes the object type and offers autocompletion.

![image](https://user-images.githubusercontent.com/6285255/103403291-e7e55c80-4b4f-11eb-9f4b-a4e19a733f84.png)

But if you return a Laravel `Collection` and iterate over it, the IDE does not recognize the class of each item and therefore the autocompletion that is one of the fundamental parts to work with this package is lost.

![image](https://user-images.githubusercontent.com/6285255/103403374-20853600-4b50-11eb-9c4d-c586e4379869.png)

Is there any way I can combine the collections with the DTOs and get autocomplete? Any Macro or anything in Laravel side?
I saw https://github.com/spatie/data-transfer-object/issues/15 but It´s a comment in first versions and I´m not sure it´s the same as I´m saying... 🙄

**Comment by mfn** [comment]
Maybe I miss understood it but the points given in https://github.com/spatie/data-transfer-object#working-with-collections should still apply? 🤔

**Comment by brendt** [comment]
You're free to make your own collection classes extending from laravel's collection class and use them as type hints. The provided DTO collection class is just a shorthand for simple use cases.
