### ISSUE TITLE
Automatically cast arrays to DTOs when creating collection.

### ISSUE THREAD

**Issue by shalvah** [spatie/data-transfer-object#158]
Hi, thanks for this package. Gets rid of a lot of boilerplate.

My current problem: I have DTOs like this:

```php
class Response extends DataTransferObject
{
    public int $status;
    public ?string $content;
    public ?string $description;
}

class ResponseCollection extends DataTransferObjectCollection
{
    public function current(): Response
    {
        return parent::current();
    }
}
```

I was kinda expecting that I could this would automatically cast each array to a `Response` object:

```php
        $responses = [
            [
                'status' => 400,
                'content' => json_encode(['id' => 6.4]),
            ],
            [
                'status' => 200,
                'content' => json_encode(['id' => 6]),
            ],
        ];
        $collection = new ResponseCollection($responses);
```

It makes sense, since the base DTO already lets you create a DTO from an array. Had to override the constructor to get that to work (but now I need to do it for all my DTOs):

```php
    public function __construct(array $collection = [])
    {
        $collection = array_map(
            fn($item) => is_array($item) ? new Response($item) : $item,
            $collection
        );

        parent::__construct($collection);
    }
```

Can I send in a PR for this? The constructor could look at the return type of `current()` and cast to that.

**Comment by shalvah** [comment]
Welp, just noticed the `arrayOf` method that can help with this. But I think it would be nice to have that behaviour as default in the future. I don't see any real downsides.

**Comment by brendt** [comment]
Does this PR solve your problem? https://github.com/spatie/data-transfer-object/pull/117

**Comment by shalvah** [comment]
Yes, I think so.
