### ISSUE TITLE
Undefined offset when dispatching DataTransferCollection to Jobs

### ISSUE THREAD

**Issue by madsem** [spatie/data-transfer-object#160]
Heyho,

I am unsure what I'm reporting here, why this even happens, if this is a bug or user error :)

Let me try to lay it out:

I have a job which makes a bigger query, with joins etc. The results are pulled as a Lazy Collection via `cursor()`.
Then `chunk(100)` and an `each()` that builds a `Spatie\DataTransferObject\DataTransferObjectCollection` from the chunk. 

This chunk is then dispatched, the handler in the next job uses a simple `foreach` loop to loop over the DTO Collection.
This here:
```php
protected OptimizableCriteriaCollection $criteria;

    /**
     * An array of key / values, needed to update Criteria models.
     *
     * @var array
     */
    protected array $optimized = [];


    /**
     * Create a new job instance.
     *
     * @param  \App\DataTransferObjects\OptimizableCriteriaCollection|\App\DataTransferObjects\OptimizableCriterionData[]  $criteria
     */
    public function __construct(OptimizableCriteriaCollection $criteria)
    {
        $this->criteria = $criteria;
    }

public function handle(OptimizeCriterionAction $optimizer)
    {
        dump($this->criteria->count());
        dump($this->criteria->current());
        foreach ($this->criteria as $criterion) {
            // Take only the key / values needed to update a Criterion model.
            $optimized = Arr::only($optimizer->execute($criterion)->toArray(), [
                'remote_account_id',
                'remote_campaign_id',
                'remote_ad_group_id',
                'remote_criterion_id',
                'name',
                'status',
                'optimized_bid',
                'paused_at',
                'match_type',
            ]);

            $optimized['optimized_bid'] = $optimized['optimized_bid']->getMinorAmount()->toInt();

            array_push($this->optimized, $optimized);
        }

        dump(count($this->optimized));

        Criterion::upsert(
            $this->optimized,
            ['remote_criterion_id', 'remote_campaign_id', 'remote_ad_group_id'],
            ['name', 'status', 'optimized_bid', 'paused_at', 'match_type']
        );
    }
```

The first job executes as it should, but all subsequent jobs simply skip the foreach loop.
I was bashing my head against the wall, trying to figure out how this could even happen that the loop is simply NOT executed.

Then I added the `dump()`'s in the handle method above, and this is the result as soon as the second job is starting to process:
```php
100
ErrorException

  Undefined offset: 0

  at vendor/spatie/data-transfer-object/src/DataTransferObjectCollection.php:27
     23▕     }
     24▕
     25▕     public function current()
     26▕     {
  ➜  27▕         return $this->collection[$this->position];
     28▕     }
     29▕
     30▕     public function offsetGet($offset)
     31▕     {

      +1 vendor frames
  2   app/DataTransferObjects/OptimizableCriteriaCollection.php:23
      Spatie\DataTransferObject\DataTransferObjectCollection::current()

  3   app/Jobs/OptimizeCriteria.php:51
      App\DataTransferObjects\OptimizableCriteriaCollection::current()
```

So the internal pointer is somehow reset or so I assume?
Is this my mistake, am I using the DTO package somehow in a way that is not standard?
Or does this seem to be unexpected behavior?

**EDIT**:
After some more playing around, when I loop like this it starts to work:
```php
foreach ($this->criteria->items() as $criterion) {
...
}
```

**Comment by brendt** [comment]
Strange indeed. If you're willing to look further into it and narrow it down, I'm fine with fixing it. But you should submit a PR with a failing test to do so, I'm don't think I'll personally look into this, since it's such an edge case.
