### ISSUE TITLE
v2.7.0 causes breaking change

### ISSUE THREAD

**Issue by fourstacks** [spatie/data-transfer-object#162]
Hi

We just had our production app go down for a bit due to a change introduced in 2.7.0.  I was hoping you might be able to shed some light on why the exception was thrown?

The exception was:

`Collection class `App\Domain\Quotes\DataTransferObjects\ItemCollection` has no defined array type.`

Our `ItemCollection` DTO looks like this:

```
<?php

namespace App\Domain\Quotes\DataTransferObjects;

use Spatie\DataTransferObject\DataTransferObjectCollection;

class ItemCollection extends DataTransferObjectCollection
{
    public function current()
    {
        return parent::current();
    }

    public static function create(array $data)
    {
        $collection = collect($data)
            ->map(function ($item) {
                return ItemData::from($item);
            })
            ->all();

        return new self($collection);
    }

    public function collect()
    {
        return collect(self::items());
    }
}
```

The context in which this DTO is used looks like this (truncated for brevity):

```
class ShippingRateRequestData extends DataTransferObject
{
    public ?ItemCollection $items;
    // other properties

    public static function from(Request $request): self
    {
        $body = json_decode($request->getContent(), true);

        $items = ItemCollection::create(Arr::get($body, 'rate.items'));

        return new self([
            'items' => $items,
            // other properties
        ]);
    }
```

I couldn't see any changes to the docs in v2.7.0 so I'm not sure if we were misusing the package prior to this update and we were just getting away with it or if this is perhaps more of a breaking change that anticipated.  Many thanks!

**Comment by brendt** [comment]
@fourstacks I'm sorry for the inconvenience! The package assume you're always type hinting the return type of the current method of DTO collections as described here: https://github.com/spatie/data-transfer-object#working-with-collections

It's true that prior to 2.7.0 no exception was thrown, but that was more due to an oversight on our part that only became clear when adding the new feature in 2.7. 

If you add a return type here, it should work:

```php
    public function current(): ItemData
    {
        return parent::current();
    }
```

Once again sorry for the trouble this caused!

**Comment by fourstacks** [comment]
Hey @brendt!  Thanks for the explanation, I'll update those collection DTOs accordingly.  

No worries about the downtime - it was a bit of a hairy 30 mins but that's on me for not having got around to sorting out any CI since we moved the app to Vapor - that's now a bit higher up my list of priorities!  Thanks again for all your work on this package (and the 3 billion others Spatie have produced).
