### ISSUE TITLE
Wrong return type in data-transfer-object/src/FieldValidator.php

### ISSUE THREAD

**Issue by rusowyler** [spatie/data-transfer-object#163]
Hi guys in getCurrentReturnTypesFromDocblock (line 185) you expect and array as return value:
 
`    private function getCurrentReturnTypesFromDocblock(string $definition): array
`

and on line 197 you may return null:

` if (! $type) {
            return null;
        }`

so if if there is doc block and no math to the preg_match it will throw a exception!

You should probably replace: return null; 
with: return [];

Hope it helps!

**Comment by brendt** [comment]
Feel free to submit a PR fixing this issue!

**Comment by brendt** [comment]
Oh, you already did; thanks!
