### ISSUE TITLE
DataTransferObjectCollection "has no defined array type"

### ISSUE THREAD

**Issue by DonCleanCode** [spatie/data-transfer-object#165]
Since the last update (2.8.0) all my Collections break with
"Spatie\DataTransferObject\DataTransferObjectError: Collection class `xxx\SampleCollection` **has no defined array type**",
no matter what kind of type it's instantiated. Before I could add DTOs and arrays, now nothing.

**Comment by mfn** [comment]
Please see https://github.com/spatie/data-transfer-object/issues/162
