### ISSUE TITLE
DataTransferColection troubles

### ISSUE THREAD

**Issue by blabs-dev** [spatie/data-transfer-object#169]
Hi, I guess this is not a proper **issue**, I don't know where to address it, so feel free to delete it if you believe that is inappropriate

I'm having troubles to build a DataTrasnferCollection from a JSON request in Laravel 6.x

## Main builder class
```php
class BulkyWasteRequestData extends DataTransferObject
{
    public int $ut_id;
    public MaterialCollection $materials;
    public CustomerData $customer_data;

    public static function fromApiRequest(BulkyWasteSubmitRequest $request) {
        return new self([
            'ut_id'         => $request->json('ut_id'),
            'materials'     => MaterialCollection::create($request->json('materials')),
            'customer_data' => new CustomerData($request->json('customer_data'))
        ]);
    }
}
```

## Collection Class
```php
class MaterialCollection extends DataTransferObjectCollection
{
    public function current(): MaterialData
    {
        return parent::current();
    }

    public static function create(array $data): MaterialCollection
    {
        return new static(MaterialData::arrayOf($data));
    }
}
```
Here I've also tryed to create the collection with a mapper that uses the `MaterialData::from()` method

```php
public static function create(array $data): MaterialCollection
    {
        $materials_collection = collect($data)->map(function ($item) {
            return MaterialData::from($item);
        });
        return new static($materials_collection->all());
    }
```
the collection is filled of theese DTOs that contains a property typed with another DTO

## Items DTO
```php
class MaterialData extends DataTransferObject
{
    public array $available_dates;
    public MaterialInfoData $info;
    public string $selected_date;

    public static function from($data) {
        return new self([
            'available_dates'   => $data['available_dates'],
            'info'              => new MaterialInfoData($data['info']),
            'selected_date'   => $data['selected_date'],
        ]);
    }
}
```
## The nested DTO
```php
class MaterialInfoData extends DataTransferObject
{
    public int $id;
    public string $uuid;
    public string $code;
    public string $type;
    public string $category;
    public string $description;
}
```

## The JSON from the request
```json
{
  "ut_id": 145,
  "materials": [
    {
      "available_dates": [
        "2021-02-19",
        "2021-02-26",
        "2021-03-12",
        "2021-03-19",
        "2021-03-26"
      ],
      "selected_date": "2021-02-19",
      "info": {
        "category": "I8",
        "code": "27",
        "description": "Fake Description",
        "id": 109,
        "type": "FAKE TYPE",
        "uuid": "6142677D-9E3B-48F5-B8FC-68D566CD1DB8"
      }
    },
    {
      "available_dates": [
        "2021-02-19",
        "2021-02-26",
        "2021-03-12",
        "2021-03-19",
        "2021-03-26"
      ],
      "selected_date": "2021-02-19",
      "info": {
        "category": "I4",
        "code": "14",
        "description": "Fake Description",
        "id": 49,
        "type": "FAKE TYPE",
        "uuid": "211E2784-1E08-4C0E-BA51-B14228D7725A"
      }
    },
    {
      "available_dates": [
        "2021-02-19",
        "2021-02-26",
        "2021-03-12",
        "2021-03-19",
        "2021-03-26"
      ],
      "selected_date": "2021-02-19",
      "info": {
        "category": "R1",
        "code": "02",
        "description": "Fake Description",
        "id": 37,
        "type": "FAKE TYPE",
        "uuid": "D1036523-2724-452A-9BF4-1DDF3DB55EAB"
      }
    }
  ],
  "customer_data": {
    "firstname": "Jonh",
    "lastname": "Doe",
    "email": "fakeuser@fakedomain.com",
    "address": "Fake Street",
    "house_number": "25",
    "zip_code": "9999",
    "phone_number": "000123456",
    "alt_phone_number": "000654321",
    "privacy": true
  }
}
```
The problem is that I always get an empty `materials` property on my `BulkyWasteRequestData` DTO, I guess that something is wrong, but I'm struggling without any clue, since the documentation about collections looks a bit unclear, I hope someone can helps me...

Thanks in advance

**Comment by mfn** [comment]
> The problem is that I always get an empty `materials` property

No error, nothing else? The collection is always empty?

Use your favourite debugger, what  does the value in `MaterialCollection::create()` receive? I suggest to step through to see it.

Also try to see if it works without `$request`, just provide the plain array with the decoded json.

If you still can't get it work, create a public minimal repo to reproduce this; ideally without the Laravel dependency.

**Comment by blabs-dev** [comment]
> Use your favourite debugger, what does the value in `MaterialCollection::create()` receive? I suggest to step through to see it.
> 
> Also try to see if it works without `$request`, just provide the plain array with the decoded json.

Already done that, the method receives an array as supposed.
Proof that everything is fine is that if I remove the `MaterialCollection` type from `materials` and replace it with `array` it works returing an array of nested items

> If you still can't get it work, create a public minimal repo to reproduce this; ideally without the Laravel dependency.
Unfortunally now I'm on a rush to close this task, so I believe that for now I'll commit the code using arrays and I'll fix it later when I'll have more time to debug it.

Thanks for your reply

**Comment by brendt** [comment]
Have you tried not using `arrayOf` and manually constructing the DTOs individually? I've never used `arrayOf` myself and there might be a bug that we're unaware of. I'm going to close this issue for now but feel free to reopen it if something new comes up.
