### ISSUE TITLE
Question about bad formed properties

### ISSUE THREAD

**Issue by Moskito89** [spatie/data-transfer-object#171]
Hey guys, 

I have problems with some kind of bad named properties. The JSON looks like that:

```
{
    "image/jpeg": "some value..."
}
```

The problem is that PHP can't have a variable name with a dash in it (`image/jpeg`), so a `DataTransferObjectError` Exception is getting thrown saying that this public property doesn't exist. 

My question is now: How can I solve that? Is there a solution to handle that kind of bad property name? Maybe some kind of function to proof and change a property's name before it gets used?

Thanks in advance!

**Comment by brendt** [comment]
The only solution I can think of is to manually prepare your data before passing it to the DTO. I personally never make use of creating DTOs from arrays on the fly to prevent these kinds of issues.

**Comment by Moskito89** [comment]
Thanks for your suggestion, that helps! 👍
