### ISSUE TITLE
Support except for nested DTO

### ISSUE THREAD

**Issue by Jurigag** [spatie/data-transfer-object#172]
When using except key for method `DataTransferObject::except()` as `something.key`, where something is another `DataTransferObject` it won'y work.

https://github.com/spatie/data-transfer-object/blob/master/src/Arr.php#L42

Here when $array[$part] is other DataTransferObject, we could use condition like:

```php
if (isset($array[$part]) && is_array($array[$part])) {
    $array = &$array[$part];
} elseif (isset($array[$part] && $array[$part] instanceof DataTransferObject) {
    $array[$part]->except(array_shift($parts));

    continue 2;
} else {
    continue 2;
}
```

**Comment by brendt** [comment]
Feel free to submit a PR with tests, it's unclear to me from this issue what the exact problem is. Thanks.
