### ISSUE TITLE
Error in field validator 

### ISSUE THREAD

**Issue by laxity7** [spatie/data-transfer-object#174]
In my company everyone writes simple comments in single line, for example:

```php
class MyDto extends \Spatie\DataTransferObject\DataTransferObject
{
    /** @var int Record some */
    public $some;
    /** @var string Record foo */
    public $foo;
    /** @var string Record bar */
    public $bar;
}
```

in this case I will get an invalid allowed type

![image](https://user-images.githubusercontent.com/6792144/111410300-87df6a80-86e9-11eb-932d-65364b60bd47.png)

And i have error:
```
The following invalid types were encountered:\nexpected `MyDto::some` to be of type `int Record some`, instead got value `123`, which is integer
```
An error in the regular expression that parses docblocks.

Do you think this is a bug that should be corrected?

**Comment by brendt** [comment]
The next major version of this package won't parse docblocks anymore but solely rely on typehints.

**Comment by mfn** [comment]
Looks like a bug to me

As a workaround, can you try:
```php
/**
 * @var int
 * Record some
 */
```
i.e. separate them.

I assume you're < 7.4? otherwise you could just write `public int $some`
