### ISSUE TITLE
Collections in v3

### ISSUE THREAD

**Issue by JuanE** [spatie/data-transfer-object#180]
How would one go about using collections in v3, now that DataTransferObjectCollection class was removed?
I understand that collections are still supported in a way but looking through the documentation I can't find an example of a collection class.
Any help would be appreciated.

**Comment by sidigi** [comment]
I think it needs examples in documentation for auto casting to collection of objects

**Comment by brendt** [comment]
There's no built-in collection support anymore. If you want your own collection classes, you'll have to implement them you'll have to implement `\ArrayAccess` and `\Iterable` and build your own. Since runtime type validation is outside the scope of this package, it doesn't make sense to add a collection class. 

My recommendation would be to typehint using an "array of docblock" and to use a static analyser instead.

**Comment by mariomka** [comment]
> My recommendation would be to typehint using an "array of docblock" and to use a static analyser instead.

But, it seems that v3 doesn't longer support array @var annotations like:

```
@var \My\Class[]
public array $myArray;
```

It doesn't cast the array items.

**Comment by brendt** [comment]
That's right, but you can create a caster for that yourself. You'd have to write it like so

```php
/** @var \My\Class[] */
#[CastWith(MyClassCollectionCaster::class)]
public array $myArray;
```

**Comment by pogush** [comment]
I'm still very much confused about this, can someone please provide an example on how to manage collections of classes/other dtos?

**Comment by brendt** [comment]
```php
```

**Comment by brendt** [comment]
I'll add this in the README as well

```php
class Bar extends DataTransferObject
{
    /** @var \Spatie\DataTransferObject\Tests\Foo[] */
    #[CastWith(FooCollectionCaster::class)]
    public array $collectionOfFoo;
}

class Foo extends DataTransferObject
{
    public string $name;
}

class FooCollectionCaster implements Caster
{
    public function cast(mixed $value): array
    {
        if (! is_array($value)) {
            throw new Exception("Can only cast arrays to Foo");
        }

        return array_map(
            fn (array $data) => new Foo(...$value),
            $value
        );
    }
}
```

Note: if you don't want to typehint `/** @var …` you'll have to implement your own collection class, there's numerous implementations out there like eg. Laravel's collection for example.

**Comment by brendt** [comment]
Full examples can be found here: https://github.com/spatie/data-transfer-object#collections-of-dtos

**Comment by pogush** [comment]
Thank you!
