### ISSUE TITLE
No validation on property change?

### ISSUE THREAD

**Issue by ValiDrv** [spatie/data-transfer-object#186]
Is there a reason the DTO validation only happens on `__construct`? 

**Example:**
```php
<?php
declare(strict_types=1);

require_once __DIR__ . '/app/vendor/autoload.php';

use Spatie\DataTransferObject\DataTransferObject;
use Spatie\DataTransferObject\Validator;
use Spatie\DataTransferObject\Validation\ValidationResult;


#[Attribute(Attribute::TARGET_PROPERTY | Attribute::IS_REPEATABLE)]
class NumberBetween implements Validator
{

    public function __construct(
        private int $min,
        private int $max
    ) {
    }

    public function validate(mixed $value): ValidationResult
    {
        echo "\n -- validate: `$value`";
        if ($value < $this->min) {
            return ValidationResult::invalid("Value should be greater than or equal to {$this->min}");
        }

        if ($value > $this->max) {
            return ValidationResult::invalid("Value should be less than or equal to {$this->max}");
        }

        return ValidationResult::valid();
    }

}

class MyDTO extends DataTransferObject
{

    #[NumberBetween(1, 100)]
    public int $a;

}

$r = new MyDTO(['a' => 5]); # Validates
$r->a = 110;                # Does not validate

```

### Suggestion
If you `unset` the public properties when the DTO is instantiated, then `__set`/`__get` will be called.

**Caveats:** 
-  `__get` will not be able to return any types other than the ones originally declared, so `array` will have to be `iterator` or `collection`... But you already have the `CollectionOfFoo` concept, so it's nothing extra.
- you cannot have any IO/context switching with libraries like Swoole in `__get`, so there should probably be a `setValue` method also.

At the very least, there should be a `validate` function that can be manually called.
```php
abstract class DataTransferObject
    ...
    public function validate() {
        $class = new DataTransferObjectClass($this); # Might want to cache this reflection
        $class->validate();
    }
    ...
}
```

**Comment by brendt** [comment]
This feature would only make sense if you don't treat your DTOs as immutable. I'm hesitant to add support for it since then we're essentially promoting mutable DTOs. I think a better solution would be somethings like this:

```php
$r = new MyDTO(['a' => 5]);
$r = $r->clone(a: 100);                # Creates a clone with new values
```

I'm going to add that right away actually. I realise it's not really a solution to your problem but like I said, we shouldn't promote mutable DTOs.

**Comment by ValiDrv** [comment]
If the DTO shouldn't be mutable, then there should be some guards against it.

Since it has public read/write properties it looks like a mutable object, and only the name "DTO" kind of hints that it should be immutable.

Can you point me to an article/why we shouldn't promote mutable DTOs? (Could not find anything about it in the V3 proposal)

**Comment by aidan-casey** [comment]
@brendt - I actually think the current behavior _does_ somewhat promote mutable DTOs and results in a pretty big loophole when considering typed objects.

I'm not sure how you'd make these truly immutable without implementing breaking changes and another release, but it does seem like something should be done here.

**Comment by brendt** [comment]
There's little we can do to improve this as long as PHP doesn't support immutable properties. My suggestion would be to use the `#[Immutable]` attribute if you really want clarity, which is supported by all major static analysis players.

In our team, we have the convention that DTOs are immutable, even though it isn't forced by the package.
