### ISSUE TITLE
Validation stops at the first invalid child in a tested structure.

### ISSUE THREAD

**Issue by ValiDrv** [spatie/data-transfer-object#187]
We use DTOs mainly for turning form post/database/queue/etc data to a know/validated object that can be used in the rest of the code (basically decode some json/array and make a DTO from it).

This means, when a DTO is instantiated with invalid data, we want to know all invalid fields, not just the first one.

**This only works on one level**, validation stops at the first invalid DTO.
Instead it should probably try to validate the entire structure, and throw an exception with all the properties that are wrong, instead of the first. 
Where the children paths could be `$parent->child->collection['index']->foo->bar: error message`

**Example:**
```php
class Foo extends DataTransferObject
{

    #[NumberBetween(1, 100)]
    public int $a;
    #[NumberBetween(1, 100)]
    public int $b;

}

$a = new Foo(['a' => 150, 'b' => 150]);
```

**Got what was expected**
```
PHP Fatal error:  Uncaught Spatie\DataTransferObject\Exceptions\ValidationException: Validation errors:
         - `Foo->a`: Value should be less than or equal to 100
         - `Foo->b`: Value should be less than or equal to 100
```

```php
class Baz extends DataTransferObject
{
    public Foo $f1;
    public Foo $f2;
}

$b = new Baz(
    [
        'f1' => ['a' => 150, 'b' => 150],
        'f2' => ['a' => 150, 'b' => 150],
    ]
);
```

**Expected** something along these lines.
```
PHP Fatal error:  Uncaught Spatie\DataTransferObject\Exceptions\ValidationException: Validation errors:
         - `Baz->f1->a`: Value should be less than or equal to 100
         - `Baz->f1->b`: Value should be less than or equal to 100
         - `Baz->f2->a`: Value should be less than or equal to 100
         - `Baz->f2->b`: Value should be less than or equal to 100
```

**But actually got**
```
PHP Fatal error:  Uncaught Spatie\DataTransferObject\Exceptions\ValidationException: Validation errors:
         - `Foo->a`: Value should be less than or equal to 100
         - `Foo->b`: Value should be less than or equal to 100
```

**Note:** This should probably also be the case if the DTO has allot of `int` properties but you try to set `strings` there.

**Comment by brendt** [comment]
This is a tricky one to solve. DTOs are individually validated, and if one's invalid, it'll throw the validation exception. So the first child gets validated, and that's where it stops. I'll think about the best solution in this case…

**Comment by brendt** [comment]
The blocker right now: `validate` is called in a DTO's constructor, so that it automatically happens whenever constructing a DTO, this is good behaviour.

We need a way to _not_ call `validate` automatically within nested DTOs though. We have an entry point to determine this (the DTO caster class), but no proper way of actually passing this info to the DTO:

- We could use `debug_backtrace`, I don't like that
- We could construct a DTO without triggering its constructor using reflection, if we're constructing the DTO within a caster, we'd have to manually set its properties then

Any other ideas?

**Comment by ValiDrv** [comment]
You put the validate in a try/catch and aggregate the exception messages.

You lose the individual exception, but that only matters if you have a bug in your validator.

**Comment by aidan-casey** [comment]
@brendt - How about taking a play out of Laravel's book and implementing some methods used in the `GuardsAttributes` trait for models, only here they would be private static methods?

For example, your construct could look like this:

```php
public function __construct(...$args)
{
    if (is_array($args[0] ?? null)) {
        $args = $args[0];
    }

    $class = new DataTransferObjectClass($this);

    foreach ($class->getProperties() as $property) {
        static::unguarded(
            fn() => $property->setValue($args[$property->name] ?? $this->{$property->name} ?? null)
        );

        unset($args[$property->name]);
    }

    if ($class->isStrict() && count($args)) {
        throw UnknownProperties::new(static::class, array_keys($args));
    }

    if (static::isGuarded()) {
        $class->validate();
    }
}
```

For clarity sake, I suppose they could also be called something along the lines of `static::withoutValidation()` and `static::shouldValidate()`.

**Comment by brendt** [comment]
> You put the validate in a try/catch and aggregate the exception messages.

@ValiDrv that would work if the parent DTO called `validate` on the child, but that's not the case since each DTO validates itself and children validate themselves first.

**Comment by brendt** [comment]
@aidan-casey I prefer not to rely on static state, but maybe you're onto something. Can you share a little more about your thought process? I'm not familiar with `GuardsAttributes`

**Comment by aidan-casey** [comment]
@brendt Yeah, I'm with you, but it does seem like it could be a good way to solve this issue.

In the GuardsAttributes trait, it has several methods that allow you to bypass the guard. One of these is the `unguarded()` method which toggles a static boolean (`$guarded`) to false, runs the callback passed to it, then toggles that static boolean back to true. It basically allows a small amount of code to be run in an isolated unguarded state.

So if you had the code below implemented, since you are calling the property `setValue` method without validation, the constructs of each child DTO will see that `shouldValidate()` equates to false. Since you are not calling that for the parent DTO though, it will run validation as normal at the end of the construct.

Example (note I revised phrasing from `unguarded` and `isGuarded` to `withoutValidation` and `shouldValidate`):

```php
private static bool $validate = true;

public static function withoutValidation(callable $callback)
{
    static::$validate = false;

    $result = $callback();

    static::$validate = true;

    return $result;
}

public static function shouldValidate(): bool
{
    return static::$validate;
}
```

This could probably be solved in a more object oriented manner as well (e.g., `setValidation(false)`) but I think that would result in more changes than necessary when the above could be implemented.

If it sounds like something you might be interested in pursuing, let me know, I am happy to work up a PR.

**Comment by brendt** [comment]
Gotcha. It's rather hacky, but then again: every other solution is as well. I'm just wondering whether it's worth adding the extra complexity only for exception messages to be a little more clear 🤔

**Comment by aidan-casey** [comment]
Yeah, I get that. The extra complexity is fairly minimal for a better developer debug experience, but I'm not sure this is a situation people will be running into often.

**Comment by ValiDrv** [comment]
Why won't something like this work:
(Stops at the first property just for simplicity)

```php
abstract class DataTransferObject
...
    public function __construct(...$args)
    {
        if (is_array($args[0] ?? null)) {
            $args = $args[0];
        }

        $class = new DataTransferObjectClass($this);

+        try {
            foreach ($class->getProperties() as $property) {
                $property->setValue($args[$property->name] ?? $this->{$property->name} ?? null); # This can fail in the caster (could be error in the caster, cast string to int, UnknownProperties, or child DTO failed validation)

                unset($args[$property->name]);
            }

            if ($class->isStrict() && count($args)) {
                throw UnknownProperties::new(static::class, array_keys($args));  # This can fail
            }

            $class->validate(); # This can fail
+        } catch (\Throwable $e) {
+            throw new \Exception(static::class . " could not be validated.\n-" . implode("\n-", explode("\n", $e->getMessage())));
+        }
    }
...
```

That way you don't need those "skip normal logic flags".
And if the thrown exception is specific to the abstract DTO class, then the message could be parsed and better formatted.

**Comment by brendt** [comment]
@ValiDrv feel free to submit a PR, the way you described doesn't work because of how validation works, but maybe there's something more to your idea that you didn't show. Here's a testcase you can use:

```php
<?php

namespace Spatie\DataTransferObject\Tests;

use Spatie\DataTransferObject\DataTransferObject;
use Spatie\DataTransferObject\Exceptions\ValidationException;
use Spatie\DataTransferObject\Tests\Dummy\NumberBetween;

class ValidationTest extends TestCase
{
    /** @test */
    public function test_validation()
    {
        $dto = new class(foo: 50) extends DataTransferObject {
            #[NumberBetween(1, 100)]
            public int $foo;
        };

//        $this->assertEquals(50, $dto->foo);

//        $this->expectException(ValidationException::class);

        new class(foo: 150) extends DataTransferObject {
            #[NumberBetween(1, 100)]
            public int $foo;
        };
    }

    /** @test */
    public function nested_validation()
    {
        $b = new NestedBaz(
            [
                'a' => ['i' => 150],
                'b' => ['i' => 150],
            ]
        );
    }
}

class NestedBaz extends DataTransferObject
{
    public NestedFoo $a;

    public NestedFoo $b;
}

class NestedFoo extends DataTransferObject
{
    #[NumberBetween(1, 100)]
    public int $i;
}
```

**Comment by brendt** [comment]
@ValiDrv it was a little more complex than that, but I got it working… in part.

The output now is this:

```
patie\DataTransferObject\Exceptions\ValidationException : Validation errors:
	 - `Spatie\DataTransferObject\Tests\NestedBaz->x`: Value should be less than or equal to 100
	 - `Spatie\DataTransferObject\Tests\NestedBaz->x`: Value should be less than or equal to 100
	 - `Spatie\DataTransferObject\Tests\NestedBaz->y`: Value should be less than or equal to 100
	 - `Spatie\DataTransferObject\Tests\NestedBaz->y`: Value should be less than or equal to 100
```

You can see the problem: `NestedBaz->x` should be `NestedBaz->a->x` etc. 

I'm going to stop looking into this for a while, there are other things higher on my priority list (but I'll come back to it later). I've pushed the changes on this branch if someone wants to take a look: https://github.com/spatie/data-transfer-object/tree/nested-validation

**Comment by ValiDrv** [comment]
Your exception needs to build a tree. And since you can't re-declare `getMessage`, you need to replicate that functionality twice, once for the current exception, once for the exception tree.

Something like this:

```php
class ValidationException extends Exception
{

    private string $_message;   # Since getMessage() is final...
    private array $exceptions;  # List of exceptions for each property.

    # Normal exception, maybe with $code
    public function __construct(string $message, Throwable ...$exceptions) {
        $this->_message   = $message;
        $this->exceptions = $exceptions;
        parent::__construct($this->formatMessage());    # Generate a pretty message for getMessage()
    }

    # Generate the getMessage message (can be prettier)
    private function formatMessage(): string {
        $tree    = self::dot($this->getTreeExceptions());
        $message = [];
        foreach ($tree as $k => $v) {
            $k         = trim($k, '.');    # Trim out the root nodes.
            $message[] = $k ? "`$k`: {$v}" : $v;
        }

        return implode(PHP_EOL, $message);
    }

    # Get a tree of exceptions. (should be a friend function...)
    public function getTreeExceptions(): array {
        $r = ['' => $this->_message];  # ROOT node, empty key.
        foreach ($this->exceptions as $k => $v) {
            if ($v instanceof self) {
                $r[$k] = $v->getTreeExceptions();   # Recursive children
            } else {
                $r[$k] = $v->getMessage();
            }
        }

        return $r;
    }

    # Just a dot notation
    private static function dot(array $array, string $delimiter = '.', string $prepend = ''): array {
        $results = [];

        foreach ($array as $key => $value) {
            if (is_array($value) && ! empty($value)) {
                $results = array_merge($results, self::dot($value, $delimiter, $prepend . $key . $delimiter));
            } else {
                $results[$prepend . $key] = $value;
            }
        }

        return $results;
    }

}


try {
    throw new ValidationException("parent exception", ...[
        'a' => new ValidationException("aaaa"),
        'b' => new ValidationException("bbb"),
        'c' => new ValidationException("cc", ...[
                'aa' => new ValidationException("aaaa1"),
                'bb' => new ValidationException("bbb1"),
                'cc' => new ValidationException("cc1"),
            ]
        ),
    ]);
} catch (ValidationException $e) {
    echo $e->getMessage();
}
```

Ps:
- Might want to add the exception `$code` in there.
- Might want to keep track of the actual exception that was thrown (ex: if you have an error in the validator/caster, you might want to see what that was)
- We use something similar, but it's in-house, and less people get to polish it. :)

**Comment by brendt** [comment]
I'll continue to work on this probably next week :)

**Comment by freekmurze** [comment]
We are stopping maintenance on this package.

Consider migrating to [spatie/laravel-data](https://spatie.be/docs/laravel-data) or [cuyz/valinor](https://github.com/cuyz/valinor)
