### ISSUE TITLE
Cache reflections in v3

### ISSUE THREAD

**Issue by mradhi** [spatie/data-transfer-object#190]
Hello,

First of all thank you very much for this amazing package. While navigating throw the source code of this library (inside the master branch [v3.x]) , I discovered we can improve the performance of casting objects by adding some cache system for the reflections used to fetch properties/classes metadata, for example inside the abstract class `DataTransferObject`, for each call to `all()` method you're performing:

```php
$class = new ReflectionClass(static::class);
$properties = $class->getProperties(ReflectionProperty::IS_PUBLIC);
...
```

Do you have some plans to integrate caching inside the v3 of this library? If yes, I can start working in a PR for this purpose.

**Comment by brendt** [comment]
Yes, feel free to send a PR!

**Comment by aidan-casey** [comment]
@mradhi - I had missed this until after I was drafting the PR this morning. Does this look like what you were after?

**Comment by mradhi** [comment]
@aidan-casey exactly, thank you for the PR

**Comment by brendt** [comment]
We're not going to add this functionality, cause benchmarks show that caching reflections only makes the tiniest difference. More info in #196
