### ISSUE TITLE
Automatic casting of nested DTOs in V3

### ISSUE THREAD

**Issue by fcoedno** [spatie/data-transfer-object#193]
I've been missing the feature of automatic casting of nested DTO, for example, in the previous version this would work:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

class FooItem extends \Spatie\DataTransferObject\DataTransferObject
{
    public string $name;
    public float $value;
}

class Foo extends \Spatie\DataTransferObject\DataTransferObject
{
    public string $name;
    /** @var FooItem[] */
    public array $items;
}

$data = [
    'name' => 'FooName',
    'items' => [
        [
            'name' => 'First',
            'value' => 42.0,
        ],
        [
            'name' => 'Second',
            'value' => 42.0,
        ],
    ]
];

$foo = new Foo($data);

var_dump($foo->name);
var_dump($foo->items[0]->name);
var_dump($foo->items[0]->value);
var_dump($foo->items[1]->name);
var_dump($foo->items[1]->value);
```

In version 2 each item is casted into a FooItem, but on version 3 that does not happen.

By reading the docs, in order to have a similar result, I would have to create a Caster class each time I need casting nested DTOs. That seems too much verbosity for something that was previously solved with a simple docblock comment.

Besides, the caster logic for this use case seems pretty straightforward, maybe it could be somehow automated. If automatic casting of nested DTO as in version 2 is not possible, creating a custom attribute to make this process easier could be an option, for example:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

class FooItem extends \Spatie\DataTransferObject\DataTransferObject
{
    public string $name;
    public float $value;
}

class Foo extends \Spatie\DataTransferObject\DataTransferObject
{
    public string $name;
    /** @var FooItem[] */
    #[CastNested(FooItem::class)]
    public array $items;
}
```

So, is this feature of automatic casting nested DTO really missing in version 3? Or am I missing something?

If this is something that could be fixed or implemented, I'm willing to do it.

**Comment by brendt** [comment]
What version are you using? This should have been fixed in 3.0.3: https://github.com/spatie/data-transfer-object/releases/tag/3.0.3

**Comment by fcoedno** [comment]
I've tested with all `3.0.*` releases

**Comment by brendt** [comment]
Please test again with at least 3.03

**Comment by sidigi** [comment]
CastNested class not found in master branch

**Comment by fcoedno** [comment]
@brendt I've tested it and the DTOs in the array are not automatically casted. Taking a look at the code regarding version `3.0.3` it seems to have handled the case for nested properties but not for automatic casting of DTOs in an array.

**Comment by aidan-casey** [comment]
@brendt - It sounds like @fcoedno is talking about casting within an array, which is not built-in to this package but can be accomplished with a caster.

Personally, I'm not of the mind to see this in the base package myself, it would be better to use a typed collection.

**Comment by fcoedno** [comment]
@aidan-casey that's indeed the case. Sorry for not making myself clearer haha.

I understand that this can be accomplished with a caster and that a typed collection is better. But my point is that the overhead to accomplish the same final result is too much in comparison to V2. If a user does not need a typed collection and just wants an array of DTO's he'll be forced to create a Caster for each array of DTO's he wants and mostly with basically the same logic and structure:

```php
class FooArrayCaster implements Caster
{
    public function cast(mixed $value): array
    {
        if (! is_array($value)) {
            throw new Exception("Can only cast arrays to Foo");
        }

        return array_map(
            fn (array $data) => new Foo(...$value),
            $value
        );
    }
}
```

So imagine the overhead of migrating from v2 to v3 when something that was accomplished with a single docblock comment now turns into a new caster class. It seems to go against the goal of (extracted from the readme) _**constructing objects from arrays of (serialized) data as easy as possible**_.

Even if it is not desired to add this behavior into the core base package, today the caster abstraction does not allow for a general purpose implementation that could be used to ease this boilerplate.

**Comment by fcoedno** [comment]
@sidigi this `CastNested` attribute I've mentioned is actually a proposal of solving this matter. Referencing the example I had given:

```php
class FooItem extends \Spatie\DataTransferObject\DataTransferObject
{
    public string $name;
    public float $value;
}

class Foo extends \Spatie\DataTransferObject\DataTransferObject
{
    public string $name;
    /** @var FooItem[] */
    #[CastNested(FooItem::class)]
    public array $items;
}
```

The base package could identify the properties marked with the `CastNested` attribute and for every element in the array automatically cast it to `FooItem::class`.

**Comment by sidigi** [comment]
>     #[CastNested(FooItem::class)]
>     public array $items;
> }

it would be cool if it can cast to collection)

```
#[CastNested(FooItem::class)]
public Collection $items;
```

**Comment by aidan-casey** [comment]
@brendt will definitely need to be the one to speak to this, but the point is that this is completely possible with this package. The package provides a framework by which you can implement casting of properties, but does not necessarily facilitate the actual means of doing so.

This package does not provide collections, so it would not make sense for it to make the decision on how to cast them. Additionally, if you are implementing a strongly typed system with DTOs, you probably shouldn't be casting to an array of them, but a typed collection.

**Comment by pikant** [comment]
> @brendt will definitely need to be the one to speak to this, but the point is that this is completely possible with this package.

Yes, but only in a super verbose fashion. When you work with APIs that have a lot of nested arrays, the switch to V3 can almost double the amount if your Dto classes. I understand your point, but currently V3 is not really usable for us because we are working almost exclusively Dtos that contain many nested arrays.

In my opinion, the package should at least give you the option to replace / extend `CastWith` so that you can write your own generic collection-caster.

**Comment by aidan-casey** [comment]
@pikant You can write your own caster by implementing `Spatie\DataTransferObject\Caster` and passing that class to the `CastWith` attribute.

**Comment by brendt** [comment]
> it would be cool if it can cast to collection)

I agree that some kind of generic cast for collections would be useful. I'm thinking about it.

**Comment by pikant** [comment]
> @pikant You can write your own caster by implementing `Spatie\DataTransferObject\Caster` and passing that class to the `CastWith` attribute.

Yes, but since `CastWith` only accepts only one parameter (in this case the class name of my custom caster class), one cannot create a generic caster. And therefore, we have to create one custom caster class for every nested array we have.

**Comment by aidan-casey** [comment]
Well, you could create a generic caster for ArrayAccess. It sounds like the problem you are describing is the ability to also cast the contents of that?

**Comment by pikant** [comment]
> Well, you could create a generic caster for ArrayAccess. It sounds like the problem you are describing is the ability to also cast the contents of that?

Exactly. Each subset / nested array should be typesafe as well. In 95% of our use cases, we have nested arrays with complex objects. Often we also have nested structures in up to three levels. That is why we absolutely need type-safe casting to Dtos. Maybe I did not point this out clearly enough. 

Here is an example:

```php
class ProductDto extends DataTransferObject
{
    public ?int $id;

    // ...

    #[CastWith(ProductVariantCollectionCaster::class)]
    public ?Collection $variants;

    #[CastWith(ProductOptionCollectionCaster::class)]
    public ?Collection $options;

    #[CastWith(ProductImageCollectionCaster::class)]
    public ?Collection $images;
```

When you now look at the customs casters, all of them are doing basically the same thing:

```php
class ProductVariantCollectionCaster implements Caster
{
    public function cast(mixed $value): Collection
    {
        return collect(array_map(
            fn (array $data) => new ProductVariantDto($data),
            $value
        ));
    }
}
```

```php
class ProductOptionCollectionCaster implements Caster
{
    public function cast(mixed $value): Collection
    {
        return collect(array_map(
            fn (array $data) => new ProductOptionDto($data),
            $value
        ));
    }
}
```

```php
class ProductImageCollectionCaster implements Caster
{
    public function cast(mixed $value): Collection
    {
        return collect(array_map(
            fn (array $data) => new ProductImageDto($data),
            $value
        ));
    }
}
```

This approach almost doubled our DTO-related classes with V3.

**Comment by fcoedno** [comment]
Maybe a possible solution would be to make the `CastWith` attribute to receive arguments and then pass these arguments to the caster constructor.

The `CastWith` attribute could start to accept a variadic arguments:

```php
#[Attribute(Attribute::TARGET_CLASS | Attribute::TARGET_PROPERTY)]
class CastWith
{
    public array $args;

    public function __construct(
        public string $casterClass,
        mixed ...$args
    ) {
        $this->args = $args;

        if (! class_implements($this->casterClass, Caster::class)) {
            throw new InvalidCasterClass($this->casterClass);
        }
    }
}
```

Using @pikant 's example, ti could be refactored to:

```php
class ProductDto extends DataTransferObject
{
    public ?int $id;

    // ...

    #[CastWith(CollectionCaster::class, targetClass: ProductVariantDto::class)]
    public ?Collection $variants;

    #[CastWith(CollectionCaster::class, targetClass: ProductOptionDto::class)]
    public ?Collection $options;

    #[CastWith(CollectionCaster::class, targetClass: ProductImageDto::class)]
    public ?Collection $images;
```

And the generic caster class:

```php
class CollectionCaster implements Caster {
    public function __construct(
        private string $type,
        private array $args
    ) {
    }

    public function cast(mixed $value): Collection
    {
        if ($this->type !== Collection::class) {
            throw new Exception("Can only cast to collections");
        }

        if (!isset($this->args['targetClass'])) {
            throw new Exception("targetClass argument is required");
        }

        return collect(array_map(fn(array $item) => new $this->args['targetClass'](...$item), $value));
    }
}
```

**Comment by brendt** [comment]
> The CastWith attribute could start to accept a variadic arguments:

I'm fine with that implementation, feel free to send a PR.
