### ISSUE TITLE
DefaultCast not repeatable

### ISSUE THREAD

**Issue by sboo** [spatie/data-transfer-object#200]
When trying to use multiple default casts as mentioned in your documentation:
```
#[
    DefaultCast(DateTimeImmutable::class, DateTimeImmutableCaster::class),
    DefaultCast(MyEnum::class, EnumCaster::class),
]

```
I get an error that the attribute must not be repeated:

`PHP Error:  Attribute "Spatie\DataTransferObject\Attributes\DefaultCast" must not be repeated in /var/www/html/vendor/spatie/data-transfer-object/src/Reflection/DataTransferObjectProperty.php on line 143`

**Comment by brendt** [comment]
Fixed in 3.1.1: https://github.com/spatie/data-transfer-object/releases/tag/3.1.1
