### ISSUE TITLE
Can I use constructor property promotion in my DTOs?

### ISSUE THREAD

**Issue by swaner** [spatie/data-transfer-object#203]
I am new to this library and I wonder if it possible to use new PHP8 feature constructor property promotion (https://www.php.net/releases/8.0/en.php#constructor-property-promotion)

```#[DefaultCast(Carbon::class, ToCarbonCaster::class)]
class CarDto extends DataTransferObject
{
    public function __construct(
        public string $name,
        public ?Carbon $launcedAt = null
    ) { }
}
```

With this in place it's very easy to construct big DTO:s with type safety and autocomplete. Syntax is same as before but the IDE will help me out with types and required properties:
```
new CarDto(
    name: 'Volvo',
    launcedAt: Carbon::now()
);
```

The issue I am running into is when converting to the DTO from array since I have overridden the constructor.
I did manage to solve this partially by creating a static function, but I really not benefiting from the library since I don't have any castings:
```
abstract class DataTransferObject
{
...
public static function fromArgs(array $args)
  {
      $reflection = new ReflectionClass(static::class);
  
      $instance = $reflection->newInstanceArgs($args);
      return $instance;
  }
}

// Usage
$dto = CarDto::fromArg(json_decode($response)); // ERROR: expected Carbon, got string
  ```

Looking into the base-class DataTransferObject I think it should be possible to support this but it would mean moving the casting functionality to a static context. If this type of factory function is added it would be optional so I don't see any need for breaking changes.

Is there any other way of solving this, or is this a feasible feature request?

**Comment by brendt** [comment]
It's not possible to support property promotion, sorry.

**Comment by swaner** [comment]
I managed get the example to work by extracting the casting resolveCaster to a static class and moving the constructor logics to it's own function.

```
abstract class DataTransferObject
{
    public function __construct(...$args)
    {
        $this->init($args);
    }

    public static function fromArgs(array $args): static
    {
        $reflection = new ReflectionClass(static::class);
        foreach ($reflection->getConstructor()->getParameters() as $parameter) {
            $property = $reflection->getProperty($parameter->name);
            if ($property && isset($args[$property->name])) {
                $caster = ResolveCasters::resolveCaster($property);
                if ($caster) {
                    $args[$property->name] = $caster->cast($args[$property->name]);
                }
            } elseif (!$parameter->isOptional()) {
                throw new \Exception('The parameter ' . $parameter->name . ' must be specified');
            }
        }
    
        $instance = $reflection->newInstanceArgs($args);
        $instance->init($args);
        return $instance;
    }
```

I do realize that this not complete and hacky atm but if you want I can submit i PR to be discussed around? But if you are 100% sure that this is not possible to support I rather not spend my time on it.

**Comment by brendt** [comment]
We really don't want to support this complexity. I'm sure there are ways around the limitations, but like you said they are hacky at best.

**Comment by swaner** [comment]
I understand your take on this. I hope you might consider it sometime in the future, it really provides a great developer experience.

Thanks for a great library.
