### ISSUE TITLE
Arguments for casters

### ISSUE THREAD

**Issue by stolentine** [spatie/data-transfer-object#205]
I suggest allowing parameters to be passed to casters

There are several ways to do this.

Version 1. Let attributes be casters. This will allow passing additional parameters to caster, such as the type for collection items.

Version 2. CastWith should accept ...$args after the $casterClass and pass them to the caster's constructor.

![image](https://user-images.githubusercontent.com/75437860/116780361-f489ab00-aa84-11eb-9c5d-a7a8a600ff17.png)

**Comment by aidan-casey** [comment]
How often is this really a use case? It seems like for scenarios where the collection should be typed it should have a dedicated collection class (e.g., "ChatThemesCollection") and other cases merit a custom caster.

If every use case is supported, this package becomes bloated where it could just be extended by creating custom caster.

**Comment by brendt** [comment]
Version 2.1 is already supported, no? https://github.com/spatie/data-transfer-object#using-custom-caster-arguments

**Comment by aidan-casey** [comment]
@brendt - It looks like the original post got edited a bit, but I believe @stolentine was recommending having a specific argument of the `CastWith` class be dedicated to parameters for the constructor of the casted class.

It seems like too much to support and you could technically do this, as you point out, with one of the parameters in the caster.
