### ISSUE TITLE
Organize Tests

### ISSUE THREAD

**Issue by aidan-casey** [spatie/data-transfer-object#207]
I am creating this as an issue because I don't want to be stepping on the toes of any standards or preferences at Spatie. I think it could be beneficial to organize tests into a file structure that matches the code being tested. This comes out of observing the standards elsewhere and my own experience with the source in which it was a little tricky to track down the right files. :sweat_smile:

Example:

- /tests/Casters/ArrayCasterTest.php

versus how it is today:

- /tests/CustomCasterArgumentsTest.php

Happy to make a PR if this is something you want to pursue.

**Comment by brendt** [comment]
I put the `ArrayCasterTest` in a separate folder because it uses some dummy classes who would otherwise have a name conflict with other dummy classes. Feel free to reorganise them. But maybe wait until I've merged all open PRs, just to make sure you don't have to deal with merge conflicts :)

**Comment by aidan-casey** [comment]
I gotcha. I'm just thinking as the project continues to develop it could be nice to have them match the structure of `src`. I'll submit a PR once the others are closed as you suggested. 🙂

**Comment by aidan-casey** [comment]
Good plan. 👍🏼
