### ISSUE TITLE
Am I misunderstanding how casters work, or is the documentation unclear?

### ISSUE THREAD

**Issue by adrienne** [spatie/data-transfer-object#211]
What i would like to do:

I have a DTO with a custom type, like this:
```php
class ItemData extends DataTransferObject
{
    use CollectableTrait;

    public int $id;
    public string $title;
    public string $url;
    public ?string $description;

    #[CastWith(EnumCaster::class)]
    public ItemStoreEnum $store;
}
```

and i am creating a DTO using a string for `$store`, like this:
```php
$itemData = new ItemData(
            id: 1,
            store: 'Target',
            url: 'https://blah.com',
            title: 'My Item'
        );
```

Now, if I understand correctly, what *should* happen is that the DTO should take the string `$store` and use `EnumCaster` to convert it to an `ItemStoreEnum`. Is that correct? Because if so, I can't get it to work at all.

**Comment by adrienne** [comment]
This whole "using specially-formatted comments to do stuff" thing is very confusing and doesn't seem to allow any way to get useful error messages, either.

**Comment by daniser** [comment]
Please show your `EnumCaster` code.
Also, don't forget to `use` both `CastWith` attribute and your `EnumCaster` caster.

**Comment by adrienne** [comment]
@daniser - the `EnumCaster` file looks like this:

```php
<?php

namespace Support\DataTransferObjects\Casters;

use Spatie\DataTransferObject\Caster;

class EnumCaster implements Caster
{
    public function __construct(
        private string $className
    ) {
    }

    public function cast(mixed $value): mixed
    {
        if ($value instanceof $this->className) {
            return $value;
        }

        return new $this->className($value);
    }
}
```

**Comment by adrienne** [comment]
@daniser - okay! It was not having the `CastWith` attribute that was causing the problem. Going to close this, but you probably want to update your documentation to make that clearer?
