### ISSUE TITLE
3.2.0 release was not released

### ISSUE THREAD

**Issue by bastien-phi** [spatie/data-transfer-object#214]
@brendt According to the Changelog, 3.2.0 was released but I cannot find the version in packagist nor the tag in github.

Maybe you just forgot to push the tag ? ;-)

A 3.2.1 release with curent master would be great too !

**Comment by brendt** [comment]
Sorry for that, and sorry for the late reply (I was on parental leave). I've tagged all changes on master as 3.2.0: https://github.com/spatie/data-transfer-object/releases/tag/3.2.0

**Comment by bastien-phi** [comment]
No worries, family comes first !

Thanks

**Comment by sandulat** [comment]
Thank you very much @brendt!
