### ISSUE TITLE
ArrayAccess limitations

### ISSUE THREAD

**Issue by aidan-casey** [spatie/data-transfer-object#216]
@swaner mentioned an issue with the `ArrayAccess` casting found in the `ArrayCaster` class in #206. I have a fix for that specific issue, but in implementing it I have discovered some oversights in my original implementation of the `ArrayAccess` caster which causes it to not work for very basic `ArrayAccess` implementations that do not also implement `IteratorAggregate`.

My current thinking is to implement some validation in the `ArrayCaster` that ensures the object also implements `IteratorAggregate`. I don't think this would really be a breaking change, as it would simply add in a check for a scenario we couldn't cover. As a bonus, we would also gain support for `ArrayObject` implementations in that caster.

@brendt - Any thoughts here? Happy to create a PR if this sounds like the right course.

**Comment by daniser** [comment]
I think you should also check if it is implementing `Iterator` instead of `IteratorAggregate`.
PS. Or better check for `Traversable` to check both cases?

**Comment by aidan-casey** [comment]
@daniser _Maybe_ in addition to, but I don't think instead of. `IteratorAggregate` exposes a method `getIterator` which returns either an instance of `Iterator` or `Traversable`. `IteratorAggregate` is used by `ArrayObject` and most collection packages out there, so I think it's going to be the more relied upon method.

There is possibly some value to supporting objects that implement `Iterator` and `Traversable` as well and it could probably be done with very little extra code, I just want to make sure we're not overcomplicating what could be a more simple class. 🙂

**Comment by daniser** [comment]
@aidan-casey That's what I meant by  saying *also*, sorry for miswording.

**Comment by aidan-casey** [comment]
@daniser  It's probably worth doing so since the same method should be able to create the objects for an `IteratorAggregate`, `Iterator`, and `Traversable`. Let's see what @brendt thinks.

**Comment by brendt** [comment]
I'm fine with fixing it, go ahead and submit a PR!

**Comment by aidan-casey** [comment]
Thanks, @brendt. I will try to have something over today.
