### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by aidan-casey** [spatie/data-transfer-object#222]
@brendt - I've been thinking about this package in light of PHP 8.1 and thought I'd create an issue with some thoughts. Don't mean to step on any toes in case you've already got something cooking.

## Immutable DTOs

With [readonly](https://wiki.php.net/rfc/readonly_properties_v2) properties coming to PHP 8.1, it seems like this would be a good time to revisit #186 and truly make DataTransferObjects immutable. I propose we do this by just adding another check for that when gathering the properties through the reflection class. This would be a breaking change.

An example of DTOs at that point would be:

```php
class PersonData extends DataTransferObject
{
    public readonly string $firstName;
    public readonly string $lastName;
    public readonly string $email;

    #[CastWith(ArrayCaster::class, itemType: AddressData::class)]
    public readonly ?array $addresses;
}
```

## Constructor Blocking

Now, as long as I'm proposing breaking changes, I want to propose a slight API change for how DTOs are created. I am proposing that the `DataTransferObject` constructor become `private` and that a new static method named `create` be `public` and `final`. This will introduce further flexibility by allowing (internally) the control over what steps are taken in the creation process.

For example, you could have something like:

```php
final public static function create(...$args): static
{
    $dto = new static(...$args);

    $dto->validate();  // Assumes a validate method exists on the DTO.

    return $dto;
}

final public static function createWithoutValidation(...$args): static
{
    $dto = new static(...$args);

    return $dto;
}
```

This can than be created with:

```php
$person = PersonData::create(
    firstName: 'Aidan',
    lastName: 'Casey',
    email: 'aidan.casey@example.com'
);
```

From the default caster you could have something like:

```php
return $this->className::createWithoutValidation(...$value);
```

By messing with validation a bit so that a default validator called `DataTransferObjectValidator` could be attached to the parent class (similar to the default caster `DataTransferObjectCaster`) the child DTOs could then be validated when the `validate()` method is called.

## Diff

Questions have been asked about tracking changes, using DTOs when making patch updates, etc. One method that may prove to be useful is a `diff()` method. This could look something like:

```php
$person = new PersonData(...);
$updatedPerson = new PersonData(...);

$changes = $updatedPerson->diff($person); // array
```

**Comment by daniser** [comment]
One argument against making constructor private is this RFC: [https://wiki.php.net/rfc/new_in_initializers](url)

In PHP 8.1, this will be perfectly valid code:
```php
class A extends DataTransferObject
{
    public string $value;
}

class B extends DataTransferObject
{
    public A $dto = new A(value: 'test');
}

echo (new B)->dto->value;
```

`test`

Without public constructor, this feature will be unavailable.

**Comment by jdreesen** [comment]
This won't work, as the mentioned RFC does not support `new` for properties (see: "Future Scope: This RFC omits support for new in property and class constant initializers. These could be supported in the future, once we have figured out the evaluation order issues.)

**Comment by aidan-casey** [comment]
> This won't work, as the mentioned RFC does not support new for properties

@jdreesen is correct here. Unfortunately, we have to drive the DTO structure through class properties which will not currently support that functionality.

@daniser one of the things I thought about was whether or not there'd be any way to support [constructor property promotion](https://wiki.php.net/rfc/constructor_promotion). That would be fantastic because then the construct method of the DTO would be type hinted and you'd be able to support scenarios like you're talking about. The problem with this is that the `DataTransferObject` abstract class really needs to be in control of setting the property values, and it would get intercepted by PHP and / or the construct of the child class.

**Comment by brendt** [comment]
> Immutable DTOs

Yes, I'm fine with a breaking change here

> Constructor Blocking

I'm not against it. I don't see how we can add property promotion btw, I've given it quite some thought already. So that shouldn't be a blocker. I think we need to poll the community beforehand though, because it could be controversial.

I'd also opt for `::new` and `::newWithoutValidation`, but that's just my preference.

> Diff

Definitely, seems like a good addition!

**Comment by aidan-casey** [comment]
> Yes, I'm fine with a breaking change here

Kinda thought you might be. 🙂 

> I'm not against it. I don't see how we can add property promotion btw, I've given it quite some thought already. So that shouldn't be a blocker. I think we need to poll the community beforehand though, because it could be controversial.

I have too and I agree. The one other argument I can think of for keeping the `__construct()` method is that it is closer to vanilla PHP as they continue to develop features like `readonly` props. I think this package has necessarily stepped into deeper functionality (casters, validation, etc.), so it's far enough from vanilla that we might as well feel comfortable stepping away from the constructor as well for more control.

**Comment by brendt** [comment]
I'll send out a tweet about it today

**Comment by brendt** [comment]
Twitter wasn't opposed to making locking the constructor, good!

**Comment by brendt** [comment]
Sidenote: we should also restructure the test suite with a new release: #207

**Comment by brendt** [comment]
As well as this one: #187

**Comment by brendt** [comment]
Another addition that might be useful: should we add more built-in validation rules? I'm sure we can get some inspiration from existing frameworks. Again, @aidan-casey has already done lots of work in this area regarding a laravel-specific DTO integration.

**Comment by brendt** [comment]
So, a quick summary of ideas for PHP 8.1:

- [ ] Readonly support
- [ ] private constructor and instead only allow static constructors (with some built-in)
- [ ] Add a `diff` method
- [ ] Restructure our test suite
- [ ] Allow to validate an entire DTO and not fail on the first failing property
- [ ] Add more built-in validation rules — maybe?

**Comment by aidan-casey** [comment]
> Another addition that might be useful: should we add more built-in validation rules? I'm sure we can get some inspiration from existing frameworks.

One concern I have here is how that would be implemented. If we provide validation rules in a framework-agnostic way, we would need to recreate the logic for the validation here in this package. If we choose to support a specific framework (e.g., Laravel), we lose the framework-agnostic element of this package.

_If validation is something we should continue to be concerned with_, I would recommend implementing validation providers. These providers would be passed the reflection properties so they could determine a valid property by attributes, type, nullable, etc.

This leaves room for releasing a minimal Laravel provider in another package. The attributes I put together could easily be extracted to another package and used there.
