### ISSUE TITLE
Add support to `NullableArrayCaster`

### ISSUE THREAD

**Issue by MatanYadaev** [spatie/data-transfer-object#223]
Currently, the `ArrayCaster` accepts only an `array|ArrayAccess`, and it fails if the value is `null`.
In my company, we need a caster that accepts `array|ArrayAccess|null` - we can't pass just an empty array because it means different thing than `null`.

Not sure if it should be a new caster, or just a flag property in the existing flag.

BTW, for now I'm using a custom caster for that, but it could be nice to have it as part of the package.

**Comment by brendt** [comment]
Feel free to submit a PR to fix it, I'm fine with a flag.
