### ISSUE TITLE
[Bug] Strict attribute is broken with version 3.6.0

### ISSUE THREAD

**Issue by Gounlaf** [spatie/data-transfer-object#226]
Hi,

It seems that the functionality `#[Strict]` is broken with version 3.6.0.
One property, or multiple ; from array or from named arguments. It always fails.

I'm just using the example from the README.

PHP Version : 8.0.9

```php
<?php

declare(strict_types=1);

require 'vendor/autoload.php';

use Spatie\DataTransferObject\Attributes\Strict;
use Spatie\DataTransferObject\DataTransferObject;

#[Strict]
class StrictDto extends DataTransferObject
{
    public string $name;
}

new StrictDto(
    name: 'name',
);

```

If I'm doing something wrong, please let me know.

Regards.

**Comment by shadowhand** [comment]
Same issue here. Despite calling the constructor with the correct arguments, it always reports the given arguments as "Unknown Properties".

**Comment by Gounlaf** [comment]
I didn't see: a PR has been made #225

**Comment by brendt** [comment]
Fixed: https://github.com/spatie/data-transfer-object/releases/tag/3.6.1
