### ISSUE TITLE
Enhanced DTOs + Linked Nested DTOs / DOM

### ISSUE THREAD

**Issue by MannikJ** [spatie/data-transfer-object#227]
Hi,

maybe there are good reasons to avoid something like this or I have overseen something that's already possible, but is there any way to get back through the structure from a nested DTO to it's parent object in a DOM fashion?

I understand and like the idea of having plain old php objects with self-validation support solving one single purpose. But I also feel it would also be a good place for some complex logic that is input-related. 

For example I think it's often a bad idea to use requests within different layers of the app, because it contains a whole lot of HTTP overhead and they are hard to create/mock/test, because this data would need to be filled somehow. The dependencies of request objects make them very inflexible.

I think DTOs would suit quite well for being enhanced with some logic and information especially from request context. For example almost any time you need at least the authenticated user model to create and assign new records from the request data. If you just fill the DTO with the request input and pass it to another layer, you would loose this information and would need to get back to the request instance which comes with the drawbacks I tried to describe above. So I think it would make sense to carry data like this within the DTO as well, so you can define strict layers and don't pollute other areas in the code with HTTP-related stuff.
So let's take the example with the authenticated user. How would you add it to the DTO? Because of its plain nature I find it hard to decide how to integrate something like this. 
And it's also related to the feature idea of DOM style DTOs, because something like the authenticated user rather belongs to the whole input object structure then to a single DTO instance. So each one of them should have access to the authenticated user.

This more a philosophical discussion, because it might be the case that I have not completely grasped the idea of DTOs and what I'm aiming for would just be abuse.

**Comment by mfn** [comment]
> How would you add it to the DTO?

I wouldn't. If I must really make sure to pass this information around _together_, I would probably _compose_ a new one bag which holds the authenticated user and the DTO.

**Comment by brendt** [comment]
I'm afraid this is outside the scope of this package.
