### ISSUE TITLE
Addition of attribute imports in examples

### ISSUE THREAD

**Issue by Shamunr** [spatie/data-transfer-object#234]
A suggestion I have would be in the examples in the README is to also include imports for attributes.  I myself had not used attributes before and was going by the examples and they were not working as expected.  The attributes I added were not being used.  It took an embarrasing amount of time to figure out that the attributes need to be imported.

In my opinion it could be a nice introduction for new users to PHP 8 and attributes to know that that must done.

**Comment by aidan-casey** [comment]
@Shamunr - This would probably be a good first PR. 🙂
