### ISSUE TITLE
Setting `#[Strict]` on parent is not applied on children

### ISSUE THREAD

**Issue by simPod** [spatie/data-transfer-object#238]
```php
#[Strict]
abstract class DtoBase {}

final class Dto extends DtoBase {}
```

then `Dto` is not strict because `DataTransferObjectClass::isStrict()` reads attributes only for current instance but not its parents. 

Is it intended or a bug? Thanks!

**Comment by brendt** [comment]
It's a bug, feel free to submit a PR that fixes it.
