### ISSUE TITLE
Question: correct place to put this logic?

### ISSUE THREAD

**Issue by 1212087** [spatie/data-transfer-object#240]
Hi everyone, 

This is a question about where is the correct place to put data transfer logic. For example, I have OrderRequest that sent from a client (Form data / Ajax), and an OrderDTO to transfer this Request.

Request: 
```
{
    order_name: "test",
    batches: [
        {
            products: [
                {
                    id: 1,
                    price: 1000
                },
                {
                    id: 2,
                    price: 2000
                }
            ],
            recipients: [
                {
                    name: 'test1'
                },
                {
                    name: 'test2'
                }
            ]
        }
    ]
}
```
OrderDTO
```php
class OrderDTO extends DataTransferObject
{
    /** @var string|null */
    public $orderName;

   /** @var \Modules\Order\DataTransferObjects\CreatingOrder\DetailDTO[] */
    public $details;
}
```
The $details in OrderDTO is something like this
```
 details: [
        {
            items: [
                {
                    id: 1,
                    price: 1000
                },
                {
                    id: 2,
                    price: 2000
                }
            ],
            receiver_name: 'test1'
        }, 
        {
             items: [
                {
                    id: 1,
                    price: 1000
                },
                {
                    id: 2,
                    price: 2000
                }
            ],
            receiver_name: 'test2'
        }
    ]
```
So I must create a function that transfers from batches to an array of DetailDTO ( $details). But where should I put this function? Inside OrderDTO such as 
```php
class OrderDTO extends DataTransferObject 
{
    public function setDetailsFromRequest(OrderRequest $request) {
         // logic
    }
}
// usage
$orderData = OrderDTO::fromRequest($request);
$orderData->setDetailsFromRequest($request);
```
Or creating an Action like this
```php
class SetOrderDTODetailsAction
{
    public function execute (OrderDTO $order, OrderRequest $request) {
        // logic
        $order->details = $transferedResult;
    }
}
// usage
$orderData = OrderDTO::fromRequest($request);
$setOrderDTODetails->execute($orderData, $request);
```
Or somewhere else...please advise

I'm new to this Pattern, so I just want to know where is the most common (and correct) place to put a logic setter function, tell me your choice and why you choose that option?

**Comment by brendt** [comment]
You should create a static method on your DTO that handles all of this at once. I'd advice against creating DTOs that require separate setter calls in order to "be complete". 

```php
$orderData = OrderDTO::fromRequest($request, /* additional data if needed to provide the details */);
```

**Comment by 1212087** [comment]
@brendt " I'd advice against creating DTOs that require separate setter calls in order to "be complete".
I agree with your opinion, but sometimes, we need DTOs that require more than one step to be completed, such as Order feature that requires many screens and requests to be completed (Fill order general information -> fill order detail -> review and confirm). What is your solution for features like this?

**Comment by brendt** [comment]
I'd create two separate DTOs, one for each step, and only combine them at the very end (possibly by storing their data in a model?)

**Comment by 1212087** [comment]
> I'd create two separate DTOs, one for each step, and only combine them at the very end (possibly by storing their data in a model?)

@brendt  Maybe something like this:
OrderStep1DTO
OrderStep2DTO
OrderStepNDTO
and OrderDTO (for final Order data) with a static function (ex: OrderDTO::fromAllPreviosStep(OrderStep1DTO, OrderStep2DTO...))
```php
class OrderDTO
{
    public static function fromPreviousSteps(OrderStep1DTO $stepOne, OrderStep2DTO $stepTwo, OrderStepNDTO $stepN) {
        // combine logic here
    }
}
```

**Comment by brendt** [comment]
I would prefer clear names like `GeneralOrderInformation` and `DetailOrderInformation`.

Besides that, I think maybe I misunderstood your use case, because the example you've shown isn't what I had in mind.

So let's back up: why do you absolutely want one combined DTO with all data in it? I can imagine that data will at some point be stored in a model somewhere, so why not simply combine it at that point?

```php
$generalData = GeneralOrderInformation::fromRequest($request);
$detailData = DetailOrderInformation::fromRequest($request);

// Somewhere in an action:

$model = Order::create(array_merge(
    $generalData->toArray(),
    $detailData->toArray(),
));
```

Backing up some more though, what still bothers me here is: why do you need several steps in the first place? Are you working with some kind of multiple requests and want to rebuild the whole DTO across sessions? That's the only reason I can come up with, you briefly mentioned AJAX but that wasn't clear from your examples.

If that is the case, then yes feel free to serialize the DTO in the session, restore it with every request and add data to it. I would use setters unless there's enough complex logic to warrant an action.

**Comment by 1212087** [comment]
"why do you need several steps in the first place? Are you working with some kind of multiple requests and want to rebuild the whole DTO across requests"
This is my use case: "Users place orders with multiple steps. In step 1, they provide some general information such as name, phone, email... In step 2, they fill detailed information such as products that they want to buy, the quantity for each product. In step 3, they review the order and confirm if all information is correct, after that, an order will actually be stored into DB. Each step is a separated screen"

"why do you absolutely want one combined DTO with all data in it? I can imagine that data will at some point be stored in a model somewhere, so why not simply combine it at that point?"
Because the order will not be stored until the user clicks confirm button on the confirmation screen, so I have to combine session data from steps 1 and 2, then show it in step 3, or store it into DB. This is a complex feature with many data and steps, the submitted data is also different from the DB structure (batches vs details). In the future, maybe more steps will be added between step 1 and the confirmation step, such as approval and payment.
I just wonder where should I place the logic function that combines data from steps, functions that transform from submitted information ($batches) to data that is actually used in my app ($details).

From your last answer, I think I can create an OrderDTO, and put combine and transform functions inside it, is that right?
```php
class OrderDTO
{
    public $name;
    public $phone;
    public $email;
    public $batches;
    public $details;

    public static function fromGeneralInformationRequest($request) : self {
        // data from step 1
        // logic set general information
    }

    public static function fromDetailedInformationRequest($request) : self {
         // data from step 2
         // logic that transform from $batches (submitted data) to $details (which actually used in app)
    }
    
    public static function fromSession() : self {
         // restore DTO from session
         // then I can use OrderDTO::fromDetailedInformationRequest() or OrderDTO::fromGeneralInformationRequest()  
         // to set data into OrderDTO
    }
}
```

**Comment by brendt** [comment]
> I think I can create an OrderDTO, and put combine and transform functions inside it, is that right?

I wouldn't have multiple static constructors, only the `fromSession` one:

```php
class OrderController
{
    public function step1(Step1Request $request)
    {
        $orderData = OrderData::new($request);

        // Store the order data in a session
    }

    public function step2(Step2Request $request)
    {
        $orderData = OrderData::fromSession(); // Maybe throw if session data is invalid?

        
        $orderData->setDetailedInformation($request); // Or use $request->validated() directly? You can choose

        // Store the order data again
    }

    …
}
```

Maybe you want to manage storing/retrieving the order data via a dedicated repository class? That's up to you.
