### ISSUE TITLE
TypeError: Cannot assign null to property PostDTO::$title of type string in file vendor\spatie\data-transfer-object\src\Reflection\DataTransferObjectProperty.php on line 48

### ISSUE THREAD

**Issue by Raja-Omer-Mustafa** [spatie/data-transfer-object#241]
TypeError: Cannot assign null to property PostDTO::$title of type string in file vendor\spatie\data-transfer-object\src\Reflection\DataTransferObjectProperty.php on line 48

I am facing this issue with PHP 8.0.9

I am using the below code am I missing something?
```
class PostDTO extends DataTransferObject
{
    #[MapFrom('postTitle')]
    public string $title;
    
    #[MapFrom('user.name')]
    public string $author;
}

$dto = new PostDTO([
    'postTitle' => 'Hello world',
    'user' => [
        'name' => 'John Doe'
    ]
]);
```

**Comment by brendt** [comment]
This might be a bug 

@MaximeWillinger you initially wrote `#[MapFrom]`, any ideas?

**Comment by Raja-Omer-Mustafa** [comment]
> This might be a bug
> 
> @MaximeWillinger you initially wrote `#[MapFrom]`, any ideas?

**Comment by Raja-Omer-Mustafa** [comment]
@brendt any feedback or updates?

**Comment by brendt** [comment]
Not yet.

**Comment by aidan-casey** [comment]
@Raja-Omer-Mustafa - You need to import the attribute. Make sure your file looks like this.

```php
use Spatie\DataTransferObject\Attributes\MapFrom;
use Spatie\DataTransferObject\DataTransferObject;

class PostDTO extends DataTransferObject
{
    #[MapFrom('postTitle')]
    public string $title;

    #[MapFrom('user.name')]
    public string $author;
}

$dto = new PostDTO([
    'postTitle' => 'Hello world',
    'user' => [
        'name' => 'John Doe'
    ]
]);
```

CC: @brendt (I believe this can be closed)

**Comment by Raja-Omer-Mustafa** [comment]
Yes that's works Great thanks
