### ISSUE TITLE
Cannot use except() after only()

### ISSUE THREAD

**Issue by mgsmus** [spatie/data-transfer-object#243]
PHP 8.0.9
Laravel 8.62.0
spatie/data-transfer-object 3.7.2 
```
class UserData extends DataTransferObject
{
    public ?string $name = null;
    public ?string $email = null;
    public ?CarbonInterface $registered_at = null;
}

```
```
$userData = new UserData([
    'name' => 'John Doe',
    'email' => 'john@doe',
    'registered_at' => now()
]);

$userData = $userData->only('name', 'email');

dd($userData->except('name')->toArray());
```
Expected response:
```
array:4 [▼
  "email" => "john@doe"
]
```
Actual response:
```
array:4 [▼
  "name" => "John Doe"
  "email" => "john@doe"
]
```

Am I missing something?

**Comment by aidan-casey** [comment]
Hey @mgsmus - those method do not currently chain. (See [line 94](https://github.com/spatie/data-transfer-object/blob/56fcac4ba39c9307a9514d49d3435f8a48409bee/src/DataTransferObject.php#L94))

If you would like to propose an API or behavioral change, #222 would be a good place to do that right now.
