### ISSUE TITLE
User ArrayCaster with itemType: Carbon?

### ISSUE THREAD

**Issue by basepack** [spatie/data-transfer-object#245]
Currently I have this DTO:

```php
class OrderFiltersData extends DataTransferObject implements Wireable
{
    #[CastWith(ArrayCaster::class, itemType: Carbon::class)]
    public ?array $days;
}
```

However when the caster runs I get the error: `Caster [ArrayCaster] each item must be an array or an instance of the specified item type [Illuminate\Support\Carbon].`

So I assumed that the casting is not what I expected. If I look into the source code for the`ArrayCaster` class, and then dump `$data` from the function `castItem(mixed $data)` then I see a Carbon string, just as I was expecting: `2021-10-06T11:30:22.989004Z`

Maybe I am understanding it wrong here, but is it not intended that the casting goes from a string to an object and vice-versa? Or is the suggested usage that ArrayCaster only uses DTO types?

**Comment by brendt** [comment]
If the individual items are arrays themselves, the package will try to cast it by using `new ItemType(...$data)` (https://github.com/spatie/data-transfer-object/blob/master/src/Casters/ArrayCaster.php#L62-L64)

So it's rather limited in that sense.

I'm not sure about the specific input, but it need to be this format:

```
$input = [
    ['2021-01-01 …'],
    ['2021-01-02 …'],
    ['2021-01-03 …'],
];
```

Hope that helps!

**Comment by basepack** [comment]
Thanks brendt for clearing that up! 

However could it not be a nice feature that if there is not an array given, `new ItemType($data)` is called?
