### ISSUE TITLE
Question: Is it possible to perform implicit model building?

### ISSUE THREAD

**Issue by Daespinosag** [spatie/data-transfer-object#257]
Hello, 

Is this package able to search a model implicitly from its identifier ? I would like to be able to pass a model object or an identifier and if I pass a valid identifier the DTO can store the model.

```
class TaskData extends DataTransferObject
{
    /**
     * TaskCategory Model
     *
     * @var TaskCategory
     */
    public TaskCategory $taskCategory;

    /**
     * Name Task
     *
     * @var string
     */
    public string $name;
}
```
for example:
I would like to be able to call them like this: 

` $taskData = new TaskData(taskCategory: 'identificator category', name: 'name');`
or
` $taskData = new TaskData(taskCategory: instanceModelTaskCategory, name: 'name');`

Is this supported by the package? is it out of scope? any ideas on how to implement it?

Thanks.

**Comment by brendt** [comment]
It's not supported and out of scope; you could always create a custom caster to handle this though :)

**Comment by Daespinosag** [comment]
**It's fine.**

I am trying to build the functionality, however I find that the `MapFrom `only recognizes one element. how can I make the `MapFrom `support two possible inputs `#[MapFrom ('model' | 'mode_id')]`. (I think it is critical to be able to do what I need). Any option that I am not considering?

Thanks for answering.
