### ISSUE TITLE
Problem with the function of converting to an array with model type properties.

### ISSUE THREAD

**Issue by Daespinosag** [spatie/data-transfer-object#258]
**Hello People.** 

Currently I have a DTO that contains a model:

```
class TaskData extends DataTransferObject
{
    /**
     * Collaborator task
     *
     * @var Collaborator|null
     */
    public Collaborator|null $collaborator;
```

Everything works fine, however when I try to convert the DTO into an array the model does not convert and is still an object. I want to answer an array in my API.

```
$taskData = new TaskData(...$parameterPackaging);
$taskData->toArray();
```

Result:

```
array:12 [
  "collaborator" => Domain\Collaborators\Models\Collaborator {#1588
```

I am doing something wrong? is this contemplated in the book store?

**Comment by nox-4O4** [comment]
If you want to recursively parse your models to arrays, all of them should extend `DataTransferObject`.

In case `Collaborator` cannot be made a `DataTransferObject` (e.g. when it should result into a scalar after making it an array), the easiest way is to override `parseArray` at your DTO class and handle objects yourself, as unfortunately currently there are no reverse casters.

So, either have your `Collaborator` class extend `DataTransferObject` or override `parseArray()`, e.g. like this:

```PHP
class TaskData extends DataTransferObject
{
    /**
     * Collaborator task
     *
     * @var Collaborator|null
     */
    public Collaborator|null $collaborator;

    protected function parseArray(array $array): array {
        foreach ($array as $key => $value) {
            if ($value instanceof Collaborator) {
                $array[$key] = $value->/* do something with collaborator here to get its array representation */;
            }
        }

        return parent::parseArray($array);
    }

```

**Comment by Daespinosag** [comment]
**Hello, thank you for replying.**

I'm not sure I understand the following recommendation: 

> If you want to recursively parse your models to arrays, all of them should extend `DataTransferObject`.

My models extend the laravel model class (they are database models).

```php
use Illuminate\Database\Eloquent\Model;

class Collaborator extends Model
{ }
```
I don't think it is possible to extend `DataTransferObject `and maintain `model `responsibility at the same time.

Did I understand your answer correctly ? am I missing something?

**Comment by brendt** [comment]
`toArray` will only cast DTOs to arrays and leave all other input alone; you can override `parseArray` in a base DTO class if you want to.
