### ISSUE TITLE
Question: Is it possible in a DTO to perform all validations before the execution is interrupted by an error?

### ISSUE THREAD

**Issue by Daespinosag** [spatie/data-transfer-object#261]
Suppose that in a DTO three variables are expected, an **identifier**, a **date** and a **number between 0 and 100**. Is there any way that if the date and the number are wrong, the DTO tells me about both errors and not only the first one it finds?

**Comment by aidan-casey** [comment]
Hey @Daespinosag,

Please see #187. This is not currently possible, though it is something that is being considered for version 4.

**Comment by Daespinosag** [comment]
**awesome, thank you**
