### ISSUE TITLE
Add support fo simple object casting

### ISSUE THREAD

**Issue by Indemnity83** [spatie/data-transfer-object#265]
Maybe I've just missed something in the documentation but it feels like simple object casting should just work. 

For example, the below throws an TypeError complaining that it cannot assign a string to the DateTime property. 

```php
use DateTime;
use Spatie\DataTransferObject\DataTransferObject;

class TokenResponse extends DataTransferObject
{
    public string $link_token;
    public DateTime $expiration;
    public string $request_id;
}
```

```php
return new TokenResponse([
    'link_token' => 'link-sandbox-af1a0311-da53-4636-b754-dd15cc058176',
    'expiration' => '2020-03-27T12:56:34Z',
    'request_id' => 'XQVgFigpGHXkb0b',
]);
```

It seems logical that when an object shall be created but the data contains a simple type only (e.g. string, float, boolean), this value is passed to the properties class constructor

Example
```php
$this->expiration = new DateTime('2020-03-27T12:56:34Z')
```

Thoughts?

**Comment by aidan-casey** [comment]
Hey @Indemnity83!

This has been discussed previously on #245 and #250. The cliff notes are basically that this is intentionally unsupported in V3, though there is a possibility of it being part of V4.

In the meantime, you can create your own caster to accomplish this functionality. 🙂

**Comment by Indemnity83** [comment]
Yeah, for now I've [created my own caster ](https://github.com/CaashApp/plaid-sdk-laravel/blob/db9e763022da8125bd27bd6b2f578dd8ed6f9567/src/Casters/DateTimeCaster.php). I'll look forward to v4, although #245 and #250 look like they still are including an annotation to drive the mapping? My point was before failing to cast, why not try using the class constructor. No annotations needed.

**Comment by aidan-casey** [comment]
Got it. I'm not sure we'll ever support that. There are a lot of edge cases involved that could have unexpected results.
