### ISSUE TITLE
[Discussion] Thoughts on using constructor property promotions?

### ISSUE THREAD

**Issue by CristianHG2** [spatie/data-transfer-object#266]
Hello! First off I'd like to take my hat off to Spatie and the other contributors for this awesome library. Thank you for keeping OSS alive!

We've built attributes that tremendously helped our Laravel development on top of this library, we are looking forward to publishing them in a few weeks or months once we know they are thoroughly tested and documented. Please look forward to that and feel free to suggest any ideas!

### Summary
More of an issue or a feature it's more of a discussion/RFC. I understand that the documentation specifies declaring the class properties in the traditional manner, however, I do think there are benefits to using property promotions instead just for better IDE/Intellisense support when actually using the DTO (_A pretty simple example of this would be TypeScript autocomplete_).

### How does it look?
At first, due to PHP's specification of named parameters, I thought flexible DTOs weren't possible using this method. A bit later I just implemented the `rest` syntax which fixed this issue. The final result looked something like this:

```php
class User extends DataTransferObject
{
    public function __construct(
        public ?string $name,
        public ?string $email,
        ...$rest
    ) {
        parent::__construct(func_get_args());
    }
}
```

Using it looked like this:
``` php
// Does not throw an error if using $rest, otherwise throws a fatal error
$user = ['name' => 'John', 'email' => 'john@doe.com', 'randomProp' => 'randomVal'];
new User(...$user);
```

This was especially useful just because our specific use-case implements DTOs as a way of standardizing different types of data, so having auto-complete and type-assisted linting when instantiating was a huge improvement. It does require a little more boilerplate though as shown above.

### So what's the point, exactly
Really just looking to discuss with contributors to get their opinion on this pattern, based on that, I'd be glad to submit a PR to include sample implementations of this pattern in the repository's README. I think it could come in very handy to just have that little piece of information easily available to new users of the library.

**Comment by aidan-casey** [comment]
Hey @CristianHG2, thanks for opening the discussion!

We are definitely proponents of property promotion in the context of data transfer objects. As you say, it improves autocomplete and type-assistance in a good IDE while accurately modeling data.

Now, all that said, this pattern is not something we are officially supporting, and we cannot guarantee it will not break at some point. For that reason, I think it is probably best to leave it unpromoted in the README, though you are free to use such an approach in your own projects.

Glad you have found a good use case for the package!
