### ISSUE TITLE
Docs for v3 not as clear as v2

### ISSUE THREAD

**Issue by garhbod** [spatie/data-transfer-object#269]
I don't know if anyone else noticed the difference but I find the Docs for version 3 throw you in the deep end straight away and don't explain the package or it's workings as well as v2.
The intro in v2 explains the reason for the package in a relatable way while giving a basic example.
On the other hand the first example in v3 uses a lot of custom classes that aren't explained and named arguments which make it appear that you can no longer simply drop in an array to be converted. Confusingly the following section "Named Arguments" contains the array example.
In my case I just want to structure the json from a api request a little better and to me v3 docs make this package look like it would be way to much effort

**Comment by brendt** [comment]
Feel free to submit a PR with things that can be improved.
