### ISSUE TITLE
Not working laravel 9

### ISSUE THREAD

**Issue by luizmagao** [spatie/data-transfer-object#275]
How working in laravel 9?

**Comment by LaravelFreelancerNL** [comment]
No problems here.

**Comment by lioneaglesolutions** [comment]
@luizmagao you might want to give some more information about why it isn't working... otherwise what do you expect Spatie to do?

**Comment by luizmagao** [comment]
now i'm working but i wanted to expand my acquaintances

**Comment by luizmagao** [comment]
Eu já consegui. Deu certinho. Obrigado amigo.
