### ISSUE TITLE
Allow mapping from multiple properties

### ISSUE THREAD

**Issue by andrzejkupczyk** [spatie/data-transfer-object#276]
Hey 👋🏻 Just wondering if it would be a good idea to allow using the `#[MapFrom]` attribute for multiple source properties?

```php
class PostDTO extends DataTransferObject
{
    #[MapFrom('type_id', 'type_name')]
    public TypeDTO $type;
}
```

Alternatively maybe it could be achieved with a new `#[MapFromMany]` attribute?

Are you willing to consider introducing such a feature?

**Comment by aidan-casey** [comment]
@andrzejkupczyk - To me, this would come across more as casting than mapping. This begs the question of whether a caster should have access to properties outside of the one it is attributed to.

I don't think this is something we will support in the current version, though perhaps in v4. In the meantime, you should be able to pass an array and use a caster to assign the properties.

**Comment by andrzejkupczyk** [comment]
@aidan-casey, thanks. You're partially right and actually using the caster was my first choice, but as you mentioned it only has access to one property. I would have to introduce an additional layer responsible for transforming the input data for the DTO to be able to use the caster... which would basically make the use of the DTO not very useful 🤷🏻
