### ISSUE TITLE
[HELP] How to cast an array of enums?

### ISSUE THREAD

**Issue by ludo237** [spatie/data-transfer-object#285]
Hello everyone.
I see that the current version has `Enumcaster` and `ArrayCaster` which are great but how can I combine them to cast an array of enumerators?

Let's say i've this scenario

```php
enum Permission : string
{
   case Foo="foo";
   case Bar="bar";
}


class MyDTO extends DataTransferObjects
{
     public array permissions;
}
```

The field `permissions` cannot use a cast like `#[CastWith(ArrayCaster::class, Permission::class)]` because then the DTO will require each single item inside `permissions` to be an instance of Permission

**Comment by aidan-casey** [comment]
@ludo237 - Use a [custom caster](https://github.com/spatie/data-transfer-object#custom-casters) or a data transfer object factory.
