### ISSUE TITLE
Optional properties

### ISSUE THREAD

**Issue by JamesHemery** [spatie/data-transfer-object#286]
Hi,

First of all thank you for all your open source work.

I'm working on a feature to add support for optional properties, like on Laravel Data. Are you ready to add this to this package (v3) ? If yes, I will open a PR :)

Looking forward to your reply,

**Comment by aidan-casey** [comment]
Hey @JamesHemery, thanks for asking! I don't think this really fits with the vision we have for this package at this time. If you need that functionality, Laravel Data may be a better option for you. 🙂
