### ISSUE TITLE
It is possible to transform enums in toArray()

### ISSUE THREAD

**Issue by Daespinosag** [spatie/data-transfer-object#288]
I am defining enum properties from DTOs in PHP 8.1. However, I am running into the problem that when I perform the transformation from DTO to array the enum fields are not transformed to text. 

```php
    /**
     * Tool code
     *
     * @var string
     */
    public ToolsEnum $tool = ToolsEnum::Core;
```

I get this: 

```php
[
 'tool' => Support\Enums\ToolsEnum::Core
]

```
but, I expect it should return this: 

```php
[
 "tool" => 'core'
]
```
For this, a `$enum->value` has to be placed in the `toArray()` method only when the property is ENUM and that enum is a key value.

I can overwrite the provided `toArray()` method, but how do I know the enum property? Has anyone had this problem? do we have any proposal?

**Comment by aidan-casey** [comment]
@Daespinosag - The `toArray()` method is _not_ a serialization mechanism. You should look at something like `symfony/serializer` for that.
