### ISSUE TITLE
Makes sense to add a class-level mapping attribute?

### ISSUE THREAD

**Issue by sirbaconjr** [spatie/data-transfer-object#292]
I've been working on a PR adding a attribute that would discover the mapped name based on a naming strategy.

Example, using a DTO like this

```php
#[MapWith(MappingStrategy::STRATEGY_SNAKE_CASE, MappingStrategy:DIRECTION_BOTH)]
class Person extends DataTransferObject
{
    public string $firstName;
}
```

Would be possible to write things like this

```php
$person = new Person(['first_name' => 'Everton']);

$person->firstName; // "Everton"

$person->toArray(); // ['first_name' => 'Everton']
```

The mapping strategies would be `snake_case`, `camelCase`, `UPPER_CASE`, `SturdyCase`.

The mapping directions would be From, To and Both.

With this, would be possible to create DTOs with a case, and generate an array with another case.

Would this be a cool addition to this library? Here is a list of things that would have to be added:

* MapWith attribute
* MappingStrategy ValueObject, to work better with the strategies
* A Str helper with functions to convert cases, this is based on Laravel Str and would require the ctype library or a polyfill for it.

For me, this feature is relevant because when working with external APIs, it's very common for them to use a different naming pattern.

**Comment by freekmurze** [comment]
We are stopping maintenance on this package.

Consider migrating to [spatie/laravel-data](https://spatie.be/docs/laravel-data) or [cuyz/valinor](https://github.com/cuyz/valinor)
