### ISSUE TITLE
Concat two properties 

### ISSUE THREAD

**Issue by codetestmg** [spatie/data-transfer-object#294]
I am using laravel-data(https://github.com/spatie/laravel-data) but I don't have the option to raise the issue there.so I thought to use this library.Both libraries are good but I have a use case where I need to contact property value with other property value .for example 

```
class SongData extends Data
{
   
    public string $firstName,
	public string $lastName,
    public string $recordCompany,

}


```
Here i want lastName value to be `firstName."-".lastName;`

is this possible using this library or laravel-data

**Comment by aidan-casey** [comment]
@codetestmg - Feel free to bring this up in the [discussions](https://github.com/spatie/laravel-data/discussions) of `spatie/laravel-data`. This repository is for `spatie/data-transfer-object`.
