### ISSUE TITLE
Adding support for strict type checks

### ISSUE THREAD

**Issue by YamenSarah** [spatie/data-transfer-object#297]
We are utilizing dtos to enforce our API contracts.
So we have a preference to not allow for type coercion. Unfortunately since this library is using reflection [setValue](https://www.php.net/manual/en/reflectionproperty.setvalue.php), our [strict_types](https://www.php.net/manual/en/language.types.declarations.php#:~:text=of%20PHP%208.0.0.-,Strict%20typing%20%C2%B6,-By%20default%2C%20PHP) declarations are ignored.

This PR adds support for strict type checks utilizing the existing Strict attribute following the same rules enforced by native strict type declarations.

I saw an older issue about this that said it would be revisited, but haven't seen anything else related.
Let us know if there is any alternative

**Comment by YamenSarah** [comment]
https://github.com/spatie/data-transfer-object/pull/293

**Comment by freekmurze** [comment]
We are stopping maintenance on this package.

Consider migrating to [spatie/laravel-data](https://spatie.be/docs/laravel-data) or [cuyz/valinor](https://github.com/cuyz/valinor)
