### ISSUE TITLE
Bug in v2: `DocblockFieldValidator` should not consider `@var mixed[]` nullable and should be a mixed array

### ISSUE THREAD

**Issue by defunctl** [spatie/data-transfer-object#306]
A class property with a Dockblock of `@var mixed[]` should not allow nullable values, and should be detected as an array:

```php
<?php declare(strict_types=1);

namespace Project\Templates\Models;

use Spatie\DataTransferObject\DataTransferObject;

class MyDto extends DataTransferObject {

	/**
	 * @var mixed[]
	 */
	public array $data = [];
	
}
```

The logic for [DocblockFieldValidator::resolveIsMixed](https://github.com/spatie/data-transfer-object/blob/a7a328f3dec64fe0270a72e1ee618923ab225f7c/src/DocblockFieldValidator.php#L66) is just checking if `mixed` is found in the string, making it detect `mixed[]` as well.

The same goes for [DocblockFieldValidator::resolveNullable](https://github.com/spatie/data-transfer-object/blob/a7a328f3dec64fe0270a72e1ee618923ab225f7c/src/DocblockFieldValidator.php#L59).

In addition to that, [DocblockFieldValidator::resolveIsMixedArray](https://github.com/spatie/data-transfer-object/blob/a7a328f3dec64fe0270a72e1ee618923ab225f7c/src/DocblockFieldValidator.php#L71), if I understand its purpose correctly, should also detect a `mixed[]` Docblock variable.

I'd be happy to submit a PR if you're open to fixing this.

Thanks for the great project!

**Comment by freekmurze** [comment]
We are stopping maintenance on this package.

Consider migrating to [spatie/laravel-data](https://spatie.be/docs/laravel-data) or [cuyz/valinor](https://github.com/cuyz/valinor)
