### ISSUE TITLE
Failed to call Class-specific casters in arrays

### ISSUE THREAD

**Issue by andrej-schaefer** [spatie/data-transfer-object#309]
Custom Class-specific casters are not called when dto is in array
In the example below the custom caster is called for the bar prop, but ignored for the $bars array

Expected behavior:
The caster is called in each case

Will try to workaround this issue somehow for now, if someone have a good workaround, youre welcome :)
Or correct me if im doing something wrong
```
class Foo extends DataTransferObject {

   public Bar $bar;

   #[CastWith(casterClass: ArrayCaster::class, itemType: Bar::class)]
   public array $bars;
}

#[CastWith(CustomCaster::class)]
class Bar extends DataTransferObject {
    ...
}
```

**Comment by freekmurze** [comment]
We are stopping maintenance on this package.

Consider migrating to [spatie/laravel-data](https://spatie.be/docs/laravel-data) or [cuyz/valinor](https://github.com/cuyz/valinor)
