### ISSUE TITLE
How to set variable `Undefined` instead of `Null`

### ISSUE THREAD

**Issue by albertcito** [spatie/data-transfer-object#310]
I have this DTO in order to save data in DB:

```php
class MyDTO extends DataTransferObject
{
    public string $email;
    public ?string $name;
    public ?string $nickname;
}
```
If I create this class:
```php
$myDTO = new MyDTO([
  "email" => "my@email.com", 
  "name" => "John Doe", 
]);
```
If I convert that DTO in array, it will return:
```php
[
  "email" => "my@email.com",
  "name" => "John",
  "nickname" => null
]
```
But it should return: 

```php
[
  "email" => "my@email.com",
  "name" => "John",
]
```

**Is there a way to don't convert possible undefined variables in NULL?**

The problem is if I have an endpoint `/user` to update the user. So user want to update his name only it will not work, because the code will `null` the nickname.

A solution could be remove the null values after cast to array. But what happens if the user want remove his nickname from the DB it will send `null`?

For now I added this function to remove the null values before to update the DB:

```php
public function toArrayRemoveNull(): array
{
  return array_filter($this->toArray(), fn ($val) => !is_null($val));
}
```

**Comment by freekmurze** [comment]
We are stopping maintenance on this package.

Consider migrating to [spatie/laravel-data](https://spatie.be/docs/laravel-data) or [cuyz/valinor](https://github.com/cuyz/valinor)
