### ISSUE TITLE
Arrays Casting to another DTO not working in Laravel 9/PHP 8.1

### ISSUE THREAD

**Issue by WordsofDefiance** [spatie/data-transfer-object#311]
I just upgraded to Laravel 9 and php 8.1. Before the upgrade, this syntax was working:

```php
DtoA $dtoA = new self(
     propertyA: 'abc',
     propertyB: ['a' => 'a', 'b' => 'b' => 'c' => 'c'], // Type: DtoB
);
```

`$dtoA` would have a property, `propertyB`, of type `DtoB`. This is the behavior described in the docs.  

After the upgrade, the array being passed to the constructor of `DtoB` is enclosed in another array -- so it looks like `[['a' => 'a', 'b' => 'b' => 'c' => 'c']]` instead of `['a' => 'a', 'b' => 'b' => 'c' => 'c']`.

Therefore, writing the constructor of `DtoB` like what is below fixes this:

```php
    public function __construct(mixed ...$args)
    {
        if (is_array($args) && is_array($args[0])) {
            $args = $args[0];
        }

        parent::__construct($args);

        $this->normalizeRefCode();
    }
```

I can't quite pinpoint where in the code the array is being enclosed by another array. If anyone knows how to fix, I'd be greatly appreciative.

**Comment by FelipeVa** [comment]
A breaking change for this was pushed on September 16. We're not sure how it was pushed to SCM since we've updated the package before and only recently experienced this issue.

We were able to fix this by downgrading the package version to `3.5`:

`"spatie/data-transfer-object": "3.5"`

**Comment by freekmurze** [comment]
We are stopping maintenance on this package.

Consider migrating to [spatie/laravel-data](https://spatie.be/docs/laravel-data) or [cuyz/valinor](https://github.com/cuyz/valinor)
