### ISSUE TITLE
Release 3.9.1 breaks embedded Data Transfer Objects

### ISSUE THREAD

**Issue by ronfuller** [spatie/data-transfer-object#312]
Embeded Data Transfer Objects are built with a single argument containing an associative array rather than expanding the attributes as separate arguments to the embedded Data Transfer Objects

Prior to 3.9.1, the code below would produce the following for the arguments to ContactDto when executing a request to create a new ContactUserDto (code below)

array:4 [
"address" => """
    7642 Botsford Wells Suite 964
    South Schuylerborough, SD 07667-8366
    """
  "city" => "Turnerbury"
  "state" => "Kansas"
  "zip" => "24189"
 ]

After 3.9.1 the same code would create the following argument to ContactDTO

array:1[
 0 => array:4 [
 "address" => """
    7642 Botsford Wells Suite 964
    South Schuylerborough, SD 07667-8366
    """
  "city" => "Turnerbury"
  "state" => "Kansas"
  "zip" => "24189"
 ]
] 
 
It appears that the embedded DTO object is not built with inflated arguments.

final class ContactDto extends DataTransferObject
{
    public string $address = '';
    public string $city = '';
    public string $state = '';
    public string $zip = '';

    public function __construct(...$args)
    {
        ray($args)->label('Contact DTO')->purple();
        parent::__construct(...$args);
    }
}

final class ContactUserDto extends DataTransferObject
{
    public string $name = '';
    public ContactDto $contact;
}

**Comment by freekmurze** [comment]
We are stopping maintenance on this package.

Consider migrating to [spatie/laravel-data](https://spatie.be/docs/laravel-data) or [cuyz/valinor](https://github.com/cuyz/valinor)
