### ISSUE TITLE
EnumCaster does not work with DefaultCast attribute

### ISSUE THREAD

**Issue by simPod** [spatie/data-transfer-object#313]
```php
#[DefaultCast(MyBackedEnum::class, EnumCaster::class)]
```

but I'm getting 

> Too few arguments to function Spatie\\DataTransferObject\\Casters\\EnumCaster::__construct(), 0 passed in /path/vendor/spatie/data-transfer-object/src/Attributes/DefaultCast.php on line 51 and exactly 2 expected"

when trying to cast a value.

But I follow the docs https://github.com/spatie/data-transfer-object#default-casters so I believe it's broken 🤔

**Comment by freekmurze** [comment]
We are stopping maintenance on this package.

Consider migrating to [spatie/laravel-data](https://spatie.be/docs/laravel-data) or [cuyz/valinor](https://github.com/cuyz/valinor)
