### ISSUE TITLE
Support namespace resolution on typed properties

### ISSUE THREAD

**Issue by mfn** [spatie/data-transfer-object#32]
The test `nested_dtos_are_automatically_cast_from_arrays_to_objects` uses `NestedParent`:
```php
class NestedParent extends DataTransferObject
{
    /** @var \Spatie\DataTransferObject\Tests\TestClasses\NestedChild */
    public $child;
    /** @var string */
    public $name;
}
```

If you either:
- import the `NestedChild` (e.g. with an alias)
- or just abbreviate it to `NestedChild` (because it's in the same namespace / directory

the code breaks:
```
1) Spatie\DataTransferObject\Tests\DataTransferObjectTest::nested_dtos_are_automatically_cast_from_arrays_to_objects
Spatie\DataTransferObject\DataTransferObjectError: Invalid type: expected Spatie\DataTransferObject\Tests\TestClasses\NestedParent::child to be of type NestedChild, instead got value `array`.
```

I think this should be supported, it's common with IDEs to no write FQN everywhere and simply use imports (even though it's in phpdoc => all relevant IDEs support this).

I found this while playing around use the new auto casting of nested DTOs feature.

**Comment by brendt** [comment]
We already had an issue for this, and even a working PR:

- https://github.com/spatie/data-transfer-object/issues/13
- https://github.com/spatie/data-transfer-object/pull/14

As you can see in the PR, adding support for class aliases introduce lots of overhead, namely file IO. We could add a lot more caching, but it would still have a significant impact on performance. 

If you have any ideas on how we could improve this: do tell us!
