### ISSUE TITLE
[SUGGESTION] Ability to ignore but preserve unknown properties

### ISSUE THREAD

**Issue by mfn** [spatie/data-transfer-object#34]
If you want to use this library to encapsulate API results which are very big but you only need a fraction of it, you still have to "type" every field which makes it less useful.

Example: Twitter.

Twitters API results are nested up to 3 or 4 levels and contain a LOTS of fields. But usually you only need some parts of it, really.

For these cases, it would be useful if:
- the DTO would only need to type the properties which are going to be used (i.e. those need to be present)
- but still would preserve the rest (when transforming back via toArray)

Right now, any properties being present in the payload but not typed throw a `DataTransferObjectError`

Just to get a feeling, here's a mock of how a event for creating a direct message with attachment can look like. It just doens't make sense to type all of it, you only need access to small parts.
```
        [
            'event' => [
                'type' => 'message_create',
                'id' => '1',
                'created_timestamp' => '1525353641112',
                'message_create' => [
                    'target' => [
                        'recipient_id' => '2',
                    ],
                    'sender_id' => '2',
                    'message_data' => [
                        'text' => 'yolo https://t.co/4T35pp33WR',
                        'entities' => [
                            'hashtags' => [],
                            'symbols' => [],
                            'user_mentions' => [],
                            'urls' => [
                                [
                                    'url' => 'https://t.co/4T35pp33WR',
                                    'expanded_url' => 'https://twitter.com/messages/media/1',
                                    'display_url' => 'pic.twitter.com/4T35pp33WR',
                                    'indices' => [
                                        0 => 5,
                                        1 => 28,
                                    ],
                                ],
                            ],
                        ],
                        'attachment' => [
                            'type' => 'media',
                            'media' => [
                                'id' => 3,
                                'id_str' => '3',
                                'indices' => [
                                    0 => 5,
                                    1 => 28,
                                ],
                                'media_url' => 'https://ton.twitter.com/1.1/ton/data/dm/1/3/RBUHkp-4.jpg',
                                'media_url_https' => 'https://ton.twitter.com/1.1/ton/data/dm/1/3/RBUHkp-4.jpg',
                                'url' => 'https://t.co/4T35pp33WR',
                                'display_url' => 'pic.twitter.com/4T35pp33WR',
                                'expanded_url' => 'https://twitter.com/messages/media/1',
                                'type' => 'photo',
                                'sizes' => [
                                    'large' => [
                                        'w' => 100,
                                        'h' => 100,
                                        'resize' => 'fit',
                                    ],
                                    'thumb' => [
                                        'w' => 100,
                                        'h' => 100,
                                        'resize' => 'crop',
                                    ],
                                    'small' => [
                                        'w' => 100,
                                        'h' => 100,
                                        'resize' => 'fit',
                                    ],
                                    'medium' => [
                                        'w' => 100,
                                        'h' => 100,
                                        'resize' => 'fit',
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ];
```

**Comment by brendt** [comment]
Interesting. Allowing unknown properties to be kept in the toArray result would reduce the safety we now get from the strong-ish typed system though. Let's consider the following example:

```php
class DummyObject extends DataTransferObject
{
    /** @var \Carbon\Carbon|null */
    public $removed_at;
}
```

Say this DTO is constructed from an API call. The `removed_at` property can either be a date or `null`, `null` meaning this object is not removed.

Now imagine this API, an external source beyond your control, makes some changes. They rename the `removed_at` field to `date_removed` instead. This should never happen of course, but I've seen many APIs before that actually make these kinds of breaking changes without notifying their consumers.

If we were to have this automatic fallback, `removed_at` would simply always be `null`, and we'd never know anything was wrong. Never, _unless_ we'd written tests for every property — that's an insane job to do.

One of the problems this package is trying to solve is to reduce the need for these kinds of tests, by using a stricter type system. Sure your production code will break no matter what, but at least you'll get a clear error which can automatically be tracked in a bug tracker. Imagine the impact if this change would go unnoticed for several days or weeks, it might have lots of side effects, which might have critical consequences for your client. 

In short, allowing this kind of fallback is not the goal of this package, actually it's the opposite. However: you give a valid example, and I _can_ tell you how to use this package with it: you'll have to do provide a mapping yourself.

```php
class TwitterEvent extends DataTransferObject
{
    /** @var string */
    public $type;

    /** @var string */
    public $created_timestamp;

    /** string */
    public $id;

    public static function fromJson(array $data): TwitterEvent
    {
        return new self([
            'type' => $data['type'],
            'created_timestamp' => $data['created_timestamp'],
            'id' => $data['id'],
        ]);
    }
}
```

Personally, I would go one step further, and cast the values to something more usable:

```php
class TwitterEvent extends DataTransferObject
{
    /** @var \Enums\TwitterEventType */
    public $type;

    /** @var \Carbon\Carbon */
    public $created_at;

    /** int */
    public $id;

    public static function fromJson(array $data): TwitterEvent
    {
        return new self([
            'type' => TwitterEventType::fromString($data['type']),
            'created_at' => Carbon::make($data['created_timestamp']),
            'id' => (int) $data['id'],
        ]);
    }
}
```

What do you think? I'm going to close this issue, as I'm certain we don't want to include this feature, but I would very much like to hear your thoughts on my arguments.

**Comment by mfn** [comment]
> Say this DTO is constructed from an API call. The `removed_at` property can either be a date or `null`, `null` meaning this object is not removed.
> 
> Now imagine this API, an external source beyond your control, makes some changes. They rename the `removed_at` field to `date_removed` instead. This should never happen of course, but I've seen many APIs before that actually make these kinds of breaking changes without notifying their consumers.

I've yet to comprehend your response 😄 but one detail I noticed:
> They rename the `removed_at` field to `date_removed` instead

and the typehint given:
> `/** @var \Carbon\Carbon|null */`

That's interesting because we potentially have three states, actually:
1) present (carbon-compatible date)
2) present with null value
3) really absent

I wonder if `null` is "good enough" for point 2) and 3).

Or should this rather be something like `void`?
> `/** @var \Carbon\Carbon|null|void */`

Just a thought.

**Comment by brendt** [comment]
`void` doesn't exist as a type. PHP 7.4 will add `uninitialized` as a state a property can be in, meaning "no value has been set". 

We allow omitting values in a DTO's constructor, when that value is nullable. It will be automatically set to `null`.

We could remove this behaviour,  but that would mean you'd always need to explicitly pass `null` values. Thinking about it, that might not be a bad idea 🤔 It would be a breaking change though..

> I've yet to comprehend your response  

How so?

**Comment by CiiDyR** [comment]
Pretty late to the party, but is this even possible with any currently available PHP version?
We'd love to use DTOs for our PATCH requests but since optional parameters will always be null, that limits us in terms of what we can represent.
To properly leverage `uninitialized` this would have to be valid (using php 8.0):

```php
class DTO
{
    public function __construct(
        public string $foo,
        public string $bar,
    ) {
    }
}
$test = new DTO(bar: 'test');
```

Our current approach would be to have a Stub class called `UndefinedValue` which we can filter out in `->all()` instead (counting on you [new 8.1 rfc](https://wiki.php.net/rfc/new_in_initializers)).
@brendt is this something that might be useful to the package in general? If so I am happy to provide a PR :)
