### ISSUE TITLE
Type `float` rejects `0` as a valid value

### ISSUE THREAD

**Issue by brettvitaz** [spatie/data-transfer-object#53]
Hello, thank you for this great library!

I am using this library in a Laravel project, and I am running into an issue. I am creating a Data Transfer Object that defines a float property and takes validated input from a Laravel route request. When a value of `0` is presented, an exception is thrown because `0` is not considered valid for a float (`0.0` works). I would very much like for the DTO to be permissive of this because we are not losing any precision, and I would not like to just include `int` as one of the types (though that does indeed work, but does not adequately represent the value). 

Is there something that I'm missing, or is this something that can be done?

**Comment by brendt** [comment]
This can be done, but we won't do it. The goal of the package is to make type validation as strict as possible. I usually add static constructors on my DTOs:

```php
public static function fromRequest(Request $request): MyDTO
{
    return new self([
        'floaty' => (float) $request->get('floaty'),
    ]);
}
```

**Comment by bvitaz-ck** [comment]
Thank you. This does not seem like an ideal solution to me, especially given the non-loss of precision. It seems to me that the property definitions is a perfect way to enforce the type safety when accessing an object, and they should be a guide on how to handle object construction which do not unnecessarily require static methods to construct the object. 

I understand that you will not fix this, and I thank you for your time. I will consider other paths to implement a solution.
