### ISSUE TITLE
Add support data validation

### ISSUE THREAD

**Issue by deviouspk** [spatie/data-transfer-object#54]
I'm often in need to validate data and doing this inside the transporter would be the best place to do it imho. Wouldn't it be nice if we could also add support for data validation. 

For example:
- property is required
- string must have min length X
- number must be greater than ..

etc

**Comment by brendt** [comment]
I see what you're saying, but validation should not be a concern of DTOs. It's business logic that should be handled by a separate class or the request (like Laravel).

I know why you want this, but we're not going to add it.

**Comment by deviouspk** [comment]
I'm aware of the original purpose of a dto as describer by martin fowler (https://martinfowler.com/eaaCatalog/dataTransferObject.html). But it just makes so much sense to put validation logic in there. If you pass data around the dto already checks for the type of each attribute. Checking if each attribute also satisfies a certain set of rules would make it so much more powerful. I basically use a dto to pass the request data from the controller to my service layer:

```
public function store(CreateScriptRequest $request)
    {
        $script = $this->service->create(new ScriptCreateDto($request->all()));
        return ScriptTransformer::resource($script);
    }
```
Having the dto take care of the validation before it enters the service layer makes the most sense imho. If you disagree could you please debate where you would put it / how you would do it? 
Best regards,
Arthur

**Comment by brendt** [comment]
Hi Arthur

In a Laravel project, I'm doing input validation in the request class or using Validators. Here's the thing: depending on where exactly you're using a DTO, the validation rules may differ. If I'm building a DTO from an admin super user's request, chances are I'll be able to do more than just a normal user. I still want to use the same DTO, but I want different rules to apply. 

I make several request classes to handle this.

**Comment by deviouspk** [comment]
I don't think it makes much sense to put validation logic in the request. This causes data being passed within the code not to be validated, only the incoming data from the user will be validated. This leads to code that is more error prone.

**Comment by brendt** [comment]
In that case you're free to make some kind of DTO factory, which handles the validation logic :)

**Comment by deviouspk** [comment]
Already on it :p

**Comment by brendt** [comment]
If you're going for the factory approach, I'm willing to consider adding it

**Comment by deviouspk** [comment]
Hi brendt,
I've quickly coded in an implementation with a factory approach for the property class (so not for the dto). Doing it for the dto doesn't solve my problems unfortunately.

what do you think about the following implementation:

```
class ValidateableDto extends DataTransferObject
{
    /** @var string */
    public $name;

    /** @var int */
    public $number;
    
    public function name(Attribute $attribute){
        return $attribute
            ->optional()
            ->rule("min:5")
            ->rule("max:30");
    }
    
    public function number(Attribute $attribute){
        return $attribute
            ->constraint(function ($value){
                return $value>5;
            });
    }
}
```

Ofcourse adding this method is completely optional so it does not introduce breaking changes.

Let me know what you think

**Comment by deviouspk** [comment]
I could also add a feature that automatically builds the attributes from a schema (https://json-schema.org/).

**Comment by denjaland** [comment]
@deviouspk I was actually going to suggest a very similar features, only I would - in line with Laravel's requests - suggest adding an optional method that returns rules:

```php
class ValidateblaDto extends DataTransferObject 
{
  public string $name;
  public int $number;

  public function rules() {
    return [
      'name' => 'required|min:2|max:63',
      'number' => 'max:100'
    ];
  }
}
```

This seems like a much easier, straight forward approach.
As I see @brendt, for the reasons he mentioned before, isn't interested in adding it to the package, I'm going to add it myself here by extending this package's class, but thought I'd just share it here, although you probably already came up with a solution by now ;-)
