### ISSUE TITLE
Improve performance by memoizing property types

### ISSUE THREAD

**Issue by yjerem** [spatie/data-transfer-object#59]
Hello, thankyou for this excellent library, it has saved me from writing so much boilerplate! :smile:

I'm wondering if there's any reason the property types of the DTO can't be memoized? Currently it re-parses all the doc comments every time you construct an instance, which seems like a lot of unnecessary work when you are creating thousands of instances.

I tried replacing [this line](https://github.com/spatie/data-transfer-object/blob/06704275d0be83f3891342c5b165aaeacb94e8de/src/DataTransferObject.php#L32) with:

```php
if (!isset(self::$properties)) {
    self::$properties = $this->getPublicProperties($class);
}
$properties = self::$properties;
```

And with that change, creating 10000 instances of a DTO goes from taking ~1.36 seconds to ~0.58 seconds. Here's my test script:

```php
class User extends DataTransferObject
{
    /** @var int */
    public $id;
    /** @var string */
    public $name1;
    /** @var string|null */
    public $name2;
    /** @var string|null */
    public $name3;
    /** @var string|null */
    public $name4;
    /** @var string|null */
    public $name5;
    /** @var string|null */
    public $name6;
    /** @var string|null */
    public $name7;
    /** @var string|null */
    public $name8;
    /** @var string|null */
    public $name9;
}

for ($i = 0; $i < 10000; $i++) {
    $user = new User(['id' => 123, 'name1' => 'Bob']);
}
```

Would this be a safe change to make, or is there a case where it would be a change in behaviour for some people? If it's a desirable change, we'd be happy to work on a proper PR for it. It would certainly make a difference for us, as we (a) are using it all over a large codebase and (b) map thousands of objects to DTOs in some places.

**Comment by sebastiandedeyne** [comment]
Hi @yjerem!

Brent, the maintainer of this package, should make the decision on whether or not this should be added, and he's afk for another week or two. Feel free to send over a PR already, but I can't promise it will get merged.

**Comment by brendt** [comment]
@yjerem sounds interesting! I'm open for a PR!

**Comment by brendt** [comment]
I've added a cache in the V2 branch: https://github.com/spatie/data-transfer-object/pull/77/commits/206ce5365ef8cc0ad275fa0517e67b42d212f268

**Comment by brendt** [comment]
Let's continue this discussion in #77
