### ISSUE TITLE
Ignoring keys that are not defined in the DTO

### ISSUE THREAD

**Issue by rgehan** [spatie/data-transfer-object#61]
I'm using `spatie/data-transfer-object` to wrap the result of a third-party API.

I totally accept the risk that they might remove a key from the result payload, in which case it would break on the instantiation of my DTO, with a really clear exception.

That behavior is fine, and what I expect.

The problem is with keys that aren't defined in the DTO.

For instance, if I define the following DTO:

```php
class MyDTO extends DataTransferObject
{
    /** @var int */
    public $a;

    /** @var int */
    public $b;
}
```

And I instantiate one like so:
```php
$data = new MyDTO(['a' => 1, 'b' => 2, 'c' => 3]);
```

It crashes, indicating that I haven't explicitly declared the `c` key.

This means that if I want to use DTOs, I have to either:
- Declare all possible keys (which is annoying because that 3rd party API returns a good hundred of keys)
- Remove these keys before instantiating my DTO (which means I have to maintain two separate list of fields: one in the DTO, one for my whitelist/blacklist).

I think a good solution would be to add the possibility for  `DataTransferObject` to simply ignore the keys it isn't aware of.

----

We would simply need to condition this line https://github.com/spatie/data-transfer-object/blob/master/src/DataTransferObject.php#L51 behind some kind of flag.

How would you feel about adding such a flag:
```diff
-public function __construct(array $parameters)
+public function __construct(array $parameters, bool $ignoreUnkownParameters = false)
```

Alternatively, we could add a `ignoreUnknownParameters` to the base class, and override it in our implementations of the DTO.

**Comment by brendt** [comment]
A similar question has been asked in the past: https://github.com/spatie/data-transfer-object/issues/34

I know some people want to do this, but it defies the goal of this package: working with data in a predictable, strongly typed way. 

We could make it "opt-in" as with your PR, but it's another piece of code we'll have to take care of from now until forever.

Now, unto a solution that might work for you: a general DTO factory. I quickly wrote this, and haven't tested it, but you should get the gist.

```php
class DataTransferObjectFactory
{
    public function make(string $dataTransferObjectClass, array $data): DataTransferObject
    {
        foreach ($data as $field => $value) {
            if (! property_exists($dataTransferObjectClass, $field)) {
                unset($data[$field]);
            }
        }

        return new $dataTransferObjectClass($data);
    }
}
```

You could add this class to your project, or even wrap it up as a standalone package. But I highly doubt it'll ever end up in this package.

You could also provide your own implementation of `DataTransferObject` in your project and do something like this:

```php
abstract class DataTransferObject extends SpatieDataTransferObject
{
    public function makeOptional(array $data): DataTransferObject
    {
        foreach ($data as $field => $value) {
            if (! property_exists($dataTransferObjectClass, $field)) {
                unset($data[$field]);
            }
        }

        return new static($data);
    }
}
```

Hope this helps!

**Comment by rgehan** [comment]
Yes, it's totally something I could do on my side, but it would have been quite nice to have by default in the package.

It doesn't make it less type-safe or predictable, as you'd still be a 100% sure all the keys you expect are defined.

It simply allows you to pass the full payload, but only retain what you care about.

This is the approach [mobx-state-tree](https://github.com/mobxjs/mobx-state-tree) uses (a JS/TS data store), and it's not any less safe.

**Comment by alsar** [comment]
@brendt your factory would only work for the root DTO. If you would have nested DTOs it would fail for those, as they would still have missing keys.

**Comment by rgehan** [comment]
My solution is simply to extend DataTransferObject, and overrides the parent constructor so that it removes all the unknown keys.

It is elegant-enough, and works with nested DTOs, even though I still feel like this should be in the package :)

**Comment by alsar** [comment]
> My solution is simply to extend DataTransferObject, and overrides the parent constructor so that it removes all the unknown keys.

I did the same. :)

**Comment by mfn** [comment]
> It simply allows you to pass the full payload, but only retain what you care about.

This is what happens in reality if you consume third party APIs. Ever worked with Facebook, YouTube, Google+, etc. APIs? Even if you didn't ask, they give you sometimes hundreds of data points which you have to ignore upfront somehow.

**Comment by brendt** [comment]
I discussed this with a few more people. While I personally would never rely on this behaviour, I realise many people do want to. We'll make it so unknown properties are ignored instead of throwing an error, in the next major version (which will be released shortly after PHP 7.4 arrives in November)

**Comment by Gummibeer** [comment]
@brendt will this be the default or enable/disable-able vie any argument? This package would get unusable for me if it would simply ignore additional properties.
Instead of an argument, I bet that this is a general setting for a whole DTO, so how about a protected property or even optional const?

**Comment by rgehan** [comment]
@Gummibeer I'm curious as to why this would get unusable for you if it suddenly ignored unknown properties.

Do you rely on it throwing when it encounters unknown keys for something?

**Comment by Gummibeer** [comment]
Exactly. I want a fully validated object - nothing more and nothing less. If I want something optional I use `|null` in the annotation. I would be even okay with having optional additional as default. But I wouldn't be okay with dropping this feature at all.

**Comment by brendt** [comment]
@Gummibeer we're only talking about input data that the DTO doesn't accept, not about missing properties. 

There are several ways we could implement it to keep both ways available, the question is which one is preferred.

- Have a dedicated static constructor that's a little more loose: `DTO::makeAndIgnoreRedundantInput()` — obviously with a better name
- Have a subclass of DTO: `DataTransferObjectWhichIgnoresRedundantInput` — again, another name
- Or have a flag in the constructor

**Comment by Gummibeer** [comment]
I would prefer a dedicated class which only defines a static property or const which could also be defined in the normal DTO with the same effect.
And yes, I know - but I also want an exception if the user tries to input too much into the DTO.

**Comment by alsar** [comment]
I also think the best solution would be to have a subclass of `DataTransferObject` for this purpose.

**Comment by brendt** [comment]
Any suggestions for a name?

**Comment by Gummibeer** [comment]
* OverloadedDataTransferObject
* AdditionalDataTransferObject
* IgnoreAdditionalDataTransferObject

**Comment by alsar** [comment]
One option would also be to do it the other way around. `DataTransferObject` for the new class where the keys are ignored and `StrictDataTransferObject` for the old behaviour.
But that probably is not possible because of BC.

**Comment by brendt** [comment]
In the end the perfect solution will depend on what side of strictness you prefer. Unfortunately for those who like a less-strict type system: I'm of the opinion that the strict option should be the default.

After reading your feedback though, I believe that the best solution is to add a static constructor on the existing DTO class, and not make a new implementation. I believe this is the best solution for both sides: the default is still the strict DTO, but getting a looser version of it is simply done with a static constructor.

**Comment by alsar** [comment]
I don't think it depends on what kind of strictness you prefer. It mainly depends on the input data you have. 
Mostly the requests for a loose version are coming from people that use DTOs with external APIs, where you would have to define a ton of useless properties that you never will use.

**Comment by brendt** [comment]
Look, the goal of this package is to _know_ what data you're working with. For example, this is how I  _always_ construct my DTOs:

```php
    public static function fromRequest(Residence $residence, OfferRequest $offerRequest): OfferData
    {
        [$invoicableType, $invoicableId] = explode(':', $offerRequest->get('invoicable_id'));

        $offerData = new self([
            'status' => $offerRequest->get('status') ?? OfferStatus::NEW,
            'residence_id' => $residence->id,
            'invoicable_type' => $invoicableType,

            'invoicable_id' => $invoicableId,
            'company_id' => $offerRequest->get('company_id'),
            'offer_date' => Carbon::make($offerRequest->get('offer_date')),
            'expiration_date' => Carbon::make($offerRequest->get('expiration_date')),
            'payment_method' => $offerRequest->get('payment_method'),
            'description' => $offerRequest->get('description'),
            'extra_info' => $offerRequest->get('extra_info'),
            'feasibility' => $offerRequest->get('feasibility') ? (int) $offerRequest->get('feasibility') : null,
            'creator_id' => $offerRequest->get('creator_id'),
            'offer_lines' => new OfferLineCollection(
                collect($offerRequest->get('offer_lines'))->map(function (array $data) use ($residence) {
                    /** @var \App\Domain\Equipment\Models\ArticleCategory $articleCategory */
                    $articleCategory = $residence->articleCategories->find($data['article_category_id']);

                    if ($data['use_existing']) {
                        [$referenceType, $referenceId] = explode(':', $data['item_id']);
                    } else {
                        $referenceType = $articleCategory->getReferenceType();
                        $referenceId = $articleCategory->getReferenceId();
                    }

                    return OfferLineData::create([
                        'id' => $data['id'] ?? null,
                        'article_category_id' => $articleCategory->id,
                        'reference_type' => $referenceType,
                        'reference_id' => $referenceId,
                        'use_existing' => $data['use_existing'] ?? false,
                        'description' => $data['description'],
                        'item_price' => (int) $data['item_price'],
                        'item_amount' => (int) $data['item_amount'],
                        'remarks' => $data['remarks'],
                        'date_start' => Carbon::make($data['date_start']),
                        'date_end' => Carbon::make($data['date_end']),
                        'time_start' => $data['time_start'],
                        'time_end' => $data['time_end'],
                    ], );
                })->toArray()
            ),
            'new_remark' => $offerRequest->get('new_remark'),
            'document_relations' => DocumentRelationCollection::create($offerRequest->get('document_relations')),
        ]);

        return $offerData;
    }
```

Is this tedious? May be. But at least I'm 100% explicit how data is mapped. Now I realise people want to use this package just for its type validation functionality. That's why I agree to adding this feature.

**Comment by mfn** [comment]
> It mainly depends on the input data you have.
> Mostly the requests for a loose version are coming from people that use DTOs with external APIs, where you would have to define a ton of useless properties that you'll never use

Wholeheartedly agree. Anyone having worked with lots of different APIs, especially from the big social media players, knows about this issue. It's simply not practical to always map everything.

**Comment by brendt** [comment]
I've got around 100 DTOs in one project, each and every one of them does a manual mapping. It is practical, because  it serves a purpose.

I'm actually writing a book about how we handle large projects at Spatie, and the second chapter is wholly dedicated to working with data, I'll let you know when it's done, in case you want to read some more background information about my point of view.

**Comment by mfn** [comment]
Regarding https://github.com/spatie/data-transfer-object/issues/61#issuecomment-537497331

Would this work with nested partial structured?

I currently too simply override the constructor with this:
```php
    /**
     * @param array<string,mixed> $parameters
     */
    public function __construct(array $parameters = [])
    {
        $class = new ReflectionClass(static::class);

        $properties = $this->getPublicProperties($class);

        foreach ($properties as $property) {
            if (
                !isset($parameters[$property->getName()]) &&
                !$property->isDefault() &&
                !$property->isNullable()
            ) {
                throw DataTransferObjectError::uninitialized($property);
            }

            $value = $parameters[$property->getName()] ?? $property->getValue($this);

            $property->set($value);
        }
    }
```
and then make all my DTOs extend this one.

**Comment by brendt** [comment]
Hello everyone. I'm working on v2, and was looking at adding this feature. There's no way to do it in a clean way without major refactors.

Once again I circle back to the goal of this package: it's meant to become obsolete as soon as PHP has a good enough type system. Right now it's missing three things which still warrant this package's existence:

- Generics
- Named parameter lists
- Union types (coming in PHP 8)

When these features are added this package _will_ be abandoned. 

If we allow ignoring properties now, it will only make things harder in the long run for those making use of this feature. I can hardly imagine that PHP will ever allow the same feature when named parameter lists are added.

So unless someone can come up with a _really_ convincing argument why the goal of this package should change, I don't think we'll add it. 

If you want to know more about my vision on how to use DTOs, you can read a recent blog post of mine on it: https://stitcher.io/blog/laravel-beyond-crud-02-working-with-data

I'll leave the issue open for another week or so. Please feel free to come up with counter arguments which haven't been given already.

**Comment by brendt** [comment]
I give up ¯\_(ツ)_/¯ too many people want this feature, even though I don't think it makes sense. I've added a `FlexibleDataTransferObject` in the v2 branch: https://github.com/spatie/data-transfer-object/pull/77/commits/aaa056fb847ffe75dfdf4793e2bec91e943b527a

**Comment by tfont** [comment]
Maybe I am a bit late to the party and sorry for scanning through all the comments above! It seems like a lot of debate over something a bit too small, with the result of a considerable impact.

DTOs should always be defined, period. Why even consider using them? That is the meaning behind them.

Perhaps consider, DDO or reconsider your code design.

**Comment by rgehan** [comment]
@tfont A lot of us are using DTOs to store the result of a 3rd-party API, which might return a lot of useless keys.

I'm dealing with an API which returns hundreds of key, while I only care about 5 of them.

I could spend time defining all of them in my DTO, but then it would break as soon as one of them is missing/added, even though I'm not even using it (and there are APIs that pull stuff like that very often).

> Perhaps consider, DDO or reconsider your code design.

I'm curious as to how you would deal with such a scenario, while still retaining the benefits of having a DTO-like typed structure?

**Comment by tfont** [comment]
@rgehan reconsider how you're managing your objects.

Be happy you aren't using a language like C#.

**Comment by simioluwatomi** [comment]
I'm also working on an application that interacts with unpredictable APIs whose response can be modified based on business needs (business needs change almost every week and custom fields are added without me knowing about them). Imagine my surprise when I come to work and a perfectly working DTO suddenly begins throwing errors!

So the current solution is to make all DTO properties nullable (which I hate) and have a very long list of properties in the DTO class. As it stands, one of my DTOs has 56 properties! Believe me, this feature is practically going to be a life-saver. Thank you

**Comment by brendt** [comment]
This is now backported to v1: https://github.com/spatie/data-transfer-object/releases/tag/1.12.0
