### ISSUE TITLE
parse DateTime and stringable objects on toArray call

### ISSUE THREAD

**Issue by Gummibeer** [spatie/data-transfer-object#64]
If the `toArray()` method is expected to return an array with only scalar types the `parseArray()` method should be extended to also handle DateTime and stringable objects.
This would handle `DateTime`, `class::toArray()` and `class::__toString()`. I've changed the already existing `toArray()` part to handle all objects that implement this method.

I can open a PR if this is wanted/expected behavior?

```php
protected function parseArray(array $array): array
{
    foreach ($array as $key => $value) {
        if (is_object($value)) {
            if($value instanceof DateTime) {
                $array[$key] = $value->format(DATE_RFC3339);

                continue;
            }

            if (method_exists($value, 'toArray')) {
                $array[$key] = $value->toArray();

                continue;
            }

            if (method_exists($value, '__toString')) {
                $array[$key] = $value->__toString();

                continue;
            }
        }

        if (! is_array($value)) {
            continue;
        }

        $array[$key] = $this->parseArray($value);
    }

    return $array;
}
```

**Comment by brendt** [comment]
Do you know by any chance know how Laravel's Eloquent `toArray` handles this? 

I almost never use `toArray` myself, so I don't have a hard opinion on it. 

Another thought coming to mind: I believe this would be a breaking change, as people using `toArray` right now don't expect it to work recursively.

**Comment by Gummibeer** [comment]
Yes it will be breaking in some kind.

It serializes dates:
https://github.com/illuminate/database/blob/275642015b1388a8dfc492f957841bc8c5223203/Eloquent/Concerns/HasAttributes.php#L123-L136

Only the `__toString()` part is added on top. 

Here you see it in action: https://github.com/Astrotomic/stancy/blob/master/src/Models/PageData.php

My goal is to have a scalar only array. The problem before was that `contents` which has a `HtmlString` instance as value would get transformed to `{}` in JSON. Now it's transformed to it's value string representation like expected (by me).
So yes, it's a very specific use case but I wanted to share it and discuss if it would be useful in the package.

**Comment by brendt** [comment]
I think it would be the right thing, we'll add this in the next major version (probably when PHP 7.4 arrives)
