### ISSUE TITLE
A few questions on correct usage

### ISSUE THREAD

**Issue by chrisbjr** [spatie/data-transfer-object#69]
Hi @brendt @freekmurze 

This is not actually an issue but questions on correct usage.

After reading @brendt 's article on [DTOs](https://stitcher.io/blog/laravel-beyond-crud-02-working-with-data), we wanted to try using this in one of our newer projects and we found that this actually helps us separate the logic for constructing data from our controllers.

Take one of our controller methods here for example:

Before DTO:
```php
public function update(UserUpdateRequest $userUpdateRequest, User $user)
{
    $this->authorize('update', $user);

    $data = $userUpdateRequest->all();

    $data['birth_date'] = Carbon::create(
        $userUpdateRequest->get('birth_date_year'),
        $userUpdateRequest->get('birth_date_month'),
        $userUpdateRequest->get('birth_date_day')
    )->format('Y-m-d');

    $city = City::find($data['city_id']);

    $data['state_id'] = $city->state->id;
    $data['region_id'] = $city->region->id;

    $user->update($data);

    event(new UserUpdated($user));

    return redirect()->route('backend.users.show', $user);
}
```

With DTO:
```php
public function update(UserUpdateRequest $userUpdateRequest, User $user)
{
    $this->authorize('update', $user);

    $data = UserUpdateData::fromRequest($userUpdateRequest);

    $user->update($data->toArray());

    event(new UserUpdated($user));

    return redirect()->route('backend.users.show', $user);
}
```

So basically we made a `UserUpdateData` DTO that looks like this:
```php
class UserUpdateData extends DataTransferObject
{
    /**
     * @var string
     */
    public $name;

    /**
     * @var string
     */
    public $username;

    /**
     * @var string
     */
    public $email;

    /**
     * @var string
     */
    public $mobile_number;

    /**
     * @var string
     */
    public $address;

    /**
     * @var int
     */
    public $city_id;

    /**
     * @var int
     */
    public $state_id;

    /**
     * @var int
     */
    public $region_id;

    /**
     * @var string|null
     */
    public $gender;

    /**
     * @var string
     */
    public $tin;

    /**
     * @var string
     */
    public $birth_date;

    public static function fromRequest(Request $request): self
    {
        $city = City::query()->find($request->get('city_id'));

        return new self([
            'username' => $request->get('username'),
            'name' => $request->get('name'),
            'email' => $request->get('email'),
            'mobile_number' => $request->get('mobile_number'),
            'gender' => $request->get('gender'),
            'tin' => $request->get('tin'),
            'address' => $request->get('address'),
            'city_id' => $city->id,
            'birth_date' => Carbon::create(
                $request->get('birth_date_year'),
                $request->get('birth_date_month'),
                $request->get('birth_date_day')
            )->format('Y-m-d'),
            'state_id' => $city->state->id,
            'region_id' => $city->region->id,
        ]);
    }
}
```

So here are our questions:

1. We decided to name this particular DTO as `UserUpdateData` because data in this object is different from creating a user. We could have a `UserCreateData` that could contain the same variables but not all of it. We looked through some examples in your projects but could not find the same pattern. Is this okay? Is this the correct way of using it?

2. Since we started this on one of our methods, should we keep following the same pattern even if the request is pretty simple? Take a look at this:

```php
class PackageUpdateData extends DataTransferObject
{
    /**
     * @var string
     */
    public $name;

    /**
     * @var string
     */
    public $prefix;

    public static function fromRequest(Request $request): self
    {
        return new self([
            'name' => $request->get('name'),
            'prefix' => $request->get('prefix'),
        ]);
    }
}
```

This doesn't change the controller but definitely adds a line there for the DTO. This helps out future developers who would like to see what's in that request but is this something that you guys skip for your projects?

3. Last concern - we've adopted camel case variable naming in our coding style and can't shake off the concern where we have to name our class variables with underscores to match to our database upon returning as an array. Could this have been a concern with you as well?

Thanks,
Chris

**Comment by brendt** [comment]
> because data in this object is different from creating a user

Sure, feel free to make separate DTOs if there's enough difference. Most often I simply add some nullable properties and use the same DTO for creation and edits. But it's up to you.

> should we keep following the same pattern even if the request is pretty simple?

I do so because:

- It keeps the codebase consistent
- Even a small DTO still offers more insights than the blackbox that is a validated request array.

Again, it's up to you. If you feel like there's more value in developing parts of your application quickly and use the request directly, you're free to do so.

> we've adopted camel case variable naming in our coding style and can't shake off the concern where we have to name our class variables with underscores to match to our database upon returning as an array. Could this have been a concern with you as well?

We had this concern as well. Ideally we'd want to use snake case for all variables, but that's a discussion for another time. The reason why we chose snake case is because we have project-specific DTO implementation which allows the user to define fillable properties. With it, a DTO can be used like so:

```php
```

**Comment by chrisbjr** [comment]
Thanks for the feedback @brendt!
