### ISSUE TITLE
Property validation

### ISSUE THREAD

**Issue by brendt** [spatie/data-transfer-object#73]
In order to properly handle caching, we want to refactor the current `Property` to allow it to be cloned. (See #66)

**Comment by brendt** [comment]
@Gummibeer asked the following in the other PR

> before I start - would this be an acceptable class signature?

```php
namespace Spatie\DataTransferObject;

class Validator
{
    public function isValidPropertyValue(DataTransferObject $dto, string $property, $value): bool
    {

    }
}
```

> Or should I change something for the primary method? I would also introduce a Caster which handles the current cast logic:

```php
if (is_array($value)) {
    $value = $this->shouldBeCastToCollection($value) ? $this->castCollection($value) : $this->cast($value);
}
```

> And to share the cached information a dedicated Cache class would also be an idea - this would also make it easier and clearer for the user to interact with the cache or even introduce his own (permanent for example) cache.

**Comment by brendt** [comment]
Here are some of my thoughts:

- I think `PropertyValidator` is a better name
- Since we'll be using the validator in the DTO constructor, I think it makes sense to add the DTO as an instance variable on the validator class
- I know we'll add caching after this so this might be a non issue, though I wonder whether we would be able initialise the reflection classes when constructing the validator class, instead of every time were calling `isValidPropertyValue`. That might not be possible if we want to clone the validator itself, though I'm not 100% sure about that.
- I agree that a caster — maybe `ValueCaster` — is a good addition also.
- Storing the cache in a separate class is also good, though I don't think we should make it configurable to the outside, that's not the goal of this package.
- We can probably add this functionality non-breaking, though maybe it's a good idea to bundle a new major version while were at it, there are some other issues we can fix.

**Comment by brendt** [comment]
As always, I'm open for all feedback!

**Comment by Gummibeer** [comment]
```php
class PropertyValidator
{
    protected $dto;

    public function __construct(DataTransferObject $dto)
    {
        $this->dto = $dto;
    }

    public function isValidPropertyValue(string $property, $value): bool;
}
```

```php
class ValueCaster
{
    protected $dto;

    public function __construct(DataTransferObject $dto)
    {
        $this->dto = $dto;
    }

    public function castPropertyValue(string $property, $value);
}
```

```php
class PropertyCache
{
    protected static $cache = [];

    public static function getInstance(): PropertyCache;

    public function getPropertyInformation(DataTransferObject $dto, string $property): array
    {
        $class = get_class($dto);

        if (!isset(static::$cache[$class])) {
            static::$cache[$class] = $this->parseDataTransferObject($dto);
        }

        return static::$cache[$class];
    }

    protected function parseDataTransferObject(DataTransferObject $dto): array;
}
```

> though I don't think we should make it configurable to the outside, that's not the goal of this package.

Having a simple `getCache()` method or injecting on runtime with an interface would be everything required for "configurable to the outside". For sure the user has to override multiple classes/methods but this way it would be possible.
Because this package is framework agnostic I scratch my had how to prevent a static only cache class? Should we use the simple old-school singleton thing? 
Implementing PSR-6 for the cache would be way too much!?

**Comment by brendt** [comment]
How about ditching the `PropertyCache::getInstance` method and making all methods static instead? 

If you'd want to roll your own implementation, one should simply extend the `DataTransferObject` class and make changes wherever they seem fit. 

PSR-6 seems like taking it a step too far, indeed 😁

**Comment by Gummibeer** [comment]
@brendt just thought about the singleton because all static is most times seen as bad practice.
I'm not against it. So if it's the only thing I will start with it. :)

**Comment by brendt** [comment]
Well… singleton is viewed equally bad 😃I think you could make the cache class abstract, to only allow static methods on it

**Comment by brendt** [comment]
@Gummibeer I'll be implementing this today

**Comment by brendt** [comment]
@Gummibeer what do you think? https://github.com/spatie/data-transfer-object/pull/77/commits/08b4c08c0b3a96699a1f63ce9a76efda29321518

**Comment by brendt** [comment]
Let's continue the discussion in #77

**Comment by Gummibeer** [comment]
@brendt looks good. :)
