### ISSUE TITLE
Immutability does not carry over to nested properties

### ISSUE THREAD

**Issue by mfn** [spatie/data-transfer-object#75]
Maybe it's a known thing and I just missed it, but they README doesn't give the obvious away to me:

> Immutability
> 
> If you want your data object to be never changeable (this is a good idea in some cases), you can make them immutable:
> ```php
> $postData = PostData::immutable([
>     'tags' => [
>         ['name' => 'foo'],
>         ['name' => 'bar']
>     ]
> ]);
> ```
> Trying to change a property of $postData after it's constructed, will result in a DataTransferObjectError.

However, if you I define a nested structure, I still can change the nested property. Immutability only affects the root DTO:
```php
class Root extends DataTransferObject {
  /** @var Nested */
  public $nested;
}
class Nested extends DataTransferObject {
  /** @var int */
  public $id;
}

$data = [
  'nested' => [
    'id' => 1,
  ]
];

$dto = Root::immutable($data);
var_dump($dto->toArray());
$dto->nested->id = 2;
var_dump($dto->toArray();
```
Output:
```
array(1) {
  ["nested"]=>
  array(1) {
    ["id"]=>
    int(1)
  }
}
array(1) {
  ["nested"]=>
  array(1) {
    ["id"]=>
    int(2)
  }
}
```
This however fails (as expected):
```php
        $dto->nested = [
            'id' => 2,
        ];
```
with
> Cannot change the value of property nested on an immutable data transfer object

**Comment by brendt** [comment]
Immutability is still a bit quirky indeed… I'll accept a PR that fixes this.

**Comment by kaiweia** [comment]
Maybe we can just hijack `ImmutableDataTransferObject` constructor?
```php
foreach (get_object_vars($dataTransferObject) as $k => $v) {
      if (is_subclass_of($v, DataTransferObject::class)) {
            $dataTransferObject->{$k} = new self($v);
      }
}
```

**Comment by brendt** [comment]
Feel free to submit a PR with tests, it should target the v2 branch though, because technically this is a breaking change.

**Comment by brendt** [comment]
Added on the v2 branch

**Comment by maxacarvalho** [comment]
@brendt sorry to comment on this issue again but as far as I understood, the below should be working, but I'm getting an exception instead  
`TypeError: Typed property App/Services/Shlink/ShortUrlDTO::$meta must be an instance of App/Services/Shlink/ShortUrlMetaDTO, Spatie/DataTransferObject/ImmutableDataTransferObject used`

Here are my two DTOs

```php
<?php

namespace App\Services\Shlink;

use Spatie\DataTransferObject\FlexibleDataTransferObject;

class ShortUrlDTO extends FlexibleDataTransferObject
{
    public string $shortCode;

    public string $shortUrl;

    public string $longUrl;

    public string $dateCreated;

    public int $visitsCount;

    public array $tags;

    public ShortUrlMetaDTO $meta;

    public ?string $domain;

    public static function fromApi(array $data): self
    {
        return static::immutable([
            'shortCode' => $data['shortCode'],
            'shortUrl' => $data['shortUrl'],
            'longUrl' => $data['longUrl'],
            'dateCreated' => $data['dateCreated'],
            'visitsCount' => $data['visitsCount'],
            'tags' => $data['tags'],
            'meta' => [
                'validSince' => data_get($data, 'meta.validSince'),
                'validUntil' => data_get($data, 'meta.validUntil'),
                'maxVisits' => data_get($data, 'meta.maxVisits'),
            ],
            'domain' => $data['domain'],
        ]);
    }
}
```

```php
<?php

namespace App\Services\Shlink;

use Spatie\DataTransferObject\FlexibleDataTransferObject;

class ShortUrlMetaDTO extends FlexibleDataTransferObject
{
    public ?string $validSince;

    public ?string $validUntil;

    public ?int $maxVisits;
}
```

Thanks!

**Comment by brendt** [comment]
Feel free to submit a PR with a failing test that should work, I'll take it from there. If you want to you can also submit a PR with the solution :)

**Comment by pepijn-de-wachter** [comment]
I was able to reproduce this today with a slightly different setup
in my case I'm using typecheck by docblock on the main DTO
also, the nested DTO was being manually constructed in the main DTO's constructor,
the constructor of the nested DTO specifically returned a `self::immutable()`

I fixed this by adding a flag to my nested DTO's constructor to allow for mutable construction


I won't be able to submit a PR today but I might be able to work something out during the weekend

**Comment by brendt** [comment]
No pressure, thanks for looking into it!

**Comment by eebanos** [comment]
> I fixed this by adding a flag to my nested DTO's constructor to allow for mutable construction
Can you show me how you did it???

**Comment by pepijn-de-wachter** [comment]
I have custom constructors for all my DTO's, so in this case for this DTO that is sometimes nested, sometimes not nested, I could add a bool to the constructor input and return an instance of self when I want a non-immutable version, which the parent DTO will then convert to an immutable one
you can set the default value of the bool to true for safety, or set it to whichever version is the most common in your use case
see redacted example code of my (most of the time) nested DTO which can be instantiated as empty:
```php
    /**
     * @param string|null $input
     * @param bool $immutable
     * @return ImmutableDataTransferObject|self
     */
    public static function fromString(?string $input, bool $immutable = true)
    {
        if ($input == null) {
            return $immutable ? self::immutable() : new self();
        }
    }
```
