### ISSUE TITLE
Tool to generate DTOs from json

### ISSUE THREAD

**Issue by atymic** [spatie/data-transfer-object#84]
Hey Brent :)

I've been using this package pretty heavily on a new project, and quickly got tired manually converting API responses into DTOs. 
Inspired by some of the json2typescript style tools, i've built a similar one for this package 😄 

It supports both docblocks & typed properties, as well as flexible DTOs (🙈).

https://json2dto.atymic.dev

I was wondering if you'd maybe consider adding it to the readme, as I think it's a pretty helpful tool!
Let me know you thoughts.

(open source as well obviously 👨‍💻)
https://github.com/atymic/json2dto

**Comment by mfn** [comment]
What license is your code?

Also I;d find it practical 😎 if it more like a library / CLI utility…

**Comment by atymic** [comment]
@mfn 

Oops, sorry added a licence :)
It'd be pretty easy to make it into a CLI util. I'll create an issue to get that done if you'd like. Would be pretty easy to split it into a composer package while i'm at it if you'd like to use it directly in your code as well.

**Comment by mfn** [comment]
> it if you'd like to use it directly in your code as well.

I think that wold be the better way, hardly can imagine devs want to use GUI tools for generating stuff.

Unrelated, just briefly checked the code, does it generate nested DTO classes or how does it handle them?

**Comment by atymic** [comment]
> I think that wold be the better way, hardly can imagine devs want to use GUI tools for generating stuff.

TBH I prefer the GUI - imo it's much easier to copy paste a json blob into the interface, select the settings and hit generate. I find it much more fiddly creating a file on the disk, then writing out the arguments to get the right settings.

It's not that hard to do both though :)

> Unrelated, just briefly checked the code, does it generate nested DTO classes or how does it handle them?

Currently it doesn't handle them (it just sets the properties to mixed/blank type). I've got it on the todo, I think it would make sense to handle that automatically. That's something that would probably work better in a cli tool, as it's a bit hard to copy paste and create multiple files :) 

Created an issue here: https://github.com/atymic/json2dto/issues/2

**Comment by brendt** [comment]
Nice one! I'd say there is potential for a command line tool, maybe as a Laravel package; though the GUI itself is already very useful. Feel free to submit a PR to the README, add it under the `Credits` section, something like

```md
## External tools

- [json2dto](https://json2dto.atymic.dev/): a GUI to convert JSON objects to DTO classes
```

**Comment by atymic** [comment]
I've released a CLI version, as per @mfn's suggestion 🎉 

I've also added support for generating nested DTOs to both the GUI and the CLI tool. 

I'll update the website shortly :)
