### ISSUE TITLE
automatic array casting to nested DTO 

### ISSUE THREAD

**Issue by nkorent** [spatie/data-transfer-object#91]
Hi,
I'm having an issue (probably of my understanding)

I've type hinted a property in my DTO as another DTO (nested DTO)
```
...
class UserData extends DataTransferObject{
...
    /** @var CompanyData */
    public $owner_company;
...
}
```

to this property I'm forwarding correct values needed for construction of CompanyData DTO but I'm getting error
```
Invalid type: expected 'App\\DataTransferObjects\\User\\UserData::owner_company' to be of type 'CompanyData', instead got value 'array', which is array.
```

Could anyone help me out to understand this a bit better or what am I doing wrong here please? :)

**Comment by mfn** [comment]
The phpdoc reference has to be absolute in the phpdoc, i.e. `\App\DataTransferObjects\CompanyData`.

It's also mentioned in the readme https://github.com/spatie/data-transfer-object/#automatic-casting-of-nested-array-dtos :
> Attention: For nested type casting to work your Docblock definition needs to be a Fully Qualified Class Name (\App\DTOs\TagData[] instead of TagData[] and an use statement at the top)

A limitation due to performance consideration of the current implementation.

**Comment by nkorent** [comment]
thanks @mfn , figgured it out later on but forgot to update status of the issue.
👍

**Comment by renepenner** [comment]
Is the automatic casting possible without phpdoc, just with php7.4 property Type?

**Comment by brendt** [comment]
I haven't tested this yet, as I never use the array casting feature myself. Feel free to write a test for it and PR it. If it fails I'll be happy to fix it.
