### ISSUE TITLE
Php 7.4 type hint for nested DTO doesn't work

### ISSUE THREAD

**Issue by ggolda** [spatie/data-transfer-object#98]
I have a DTO structure as below:

```php
class AssetDescription extends DataTransferObject
{
    public string $object_type;
    public string $name;
    public ?string $folder_id;

    public Metadata $metadata;
}

class Metadata extends DataTransferObject
{
    public int $size;
}
```

And when I construct DTO from array it throws error:
```
"message": "Typed property App\\Domains\\Assets\\DTO\\AssetDescription::$metadata must be an instance of App\\Domains\\Assets\\DTO\\Metadata, array used",
```

Works if I use a `@var` docblock.

**Comment by brendt** [comment]
Feel free to submit a PR with a fix.

**Comment by skyrpex** [comment]
@brendt I'll give it a try. How would you like to approach this? The `FieldValidator` only understands doc comments. Should I create two different validators and a interface, or maybe supercharge the existing validator?

**Comment by brendt** [comment]
Some valid points. I'll take a closer look when I've got some spare time.

**Comment by brendt** [comment]
I'll merge https://github.com/spatie/data-transfer-object/pull/106 today
